import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    home: 'Home',
    services: 'Services',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    getStarted: 'Get Started',
    myProfile: 'My Profile',
    signOut: 'Sign Out',
    adminPanel: 'Admin Panel',
    bookService: 'Book Service',
    myBookings: 'My Bookings',
    jobRequests: 'Job Requests',
    dashboard: 'Dashboard',
    workers: 'Workers',
    support: 'Support',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    faqs: 'FAQs',
    bookings: 'Bookings',
    jobs: 'Jobs',
    book: 'Book',
    profile: 'Profile',
    ourBlog: 'Our Blog',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    newsletter: 'Newsletter',
    newsletterPlaceholder: 'Your email',
    allRightsReserved: 'All rights reserved.',
    footerDesc: 'Service Knock is your premier hyper-local service booking platform, dedicated to connecting you with highly skilled and trusted professionals in your area. We provide reliable solutions for all your home and business needs, ensuring quality service is just a few clicks away.',
    addressFull: '123 Service Lane, Tech City, 10001',
    ac_fridge_repair: 'AC / Fridge Repair',
    steel_fixer: 'Steel Fixer',
    tile_fixer: 'Tile Fixer',
    irfanRashid: 'Irfan Rashid',
    irfanrashid: 'Irfan Rashid',
    'Irfan Rashid': 'Irfan Rashid',
    khurshidAhmedKhan: 'Khurshid Ahmed Khan',
    'Khurshid Ahmed Khan': 'Khurshid Ahmed Khan',
    serviceTapAdmin: 'ServiceTap Admin',
    serviceKnockAdmin: 'Service Knock Admin',
    
    // Hero Section
    heroTitle: 'Professional Home Services at Your Doorstep',
    heroSubtitle: 'Book trusted electricians, plumbers, painters and more in just a few taps. Reliable help for every home need.',
    heroCTA: 'Book a Service Now',
    activePros: 'Active Professionals',
    trustedUsers: 'Trusted Users',
    
    // Services Section
    ourServices: 'Our Services',
    servicesSubtitle: 'We provide a wide range of professional home services to help you with your daily needs.',
    electrician: 'Electrician',
    plumber: 'Plumber',
    ac_fridge_repair: 'AC / Fridge Repair',
    carpenter: 'Carpenter',
    painter: 'Painter',
    mason: 'Mason',
    steel_fixer: 'Steel Fixer',
    labour: 'Labour',
    tile_fixer: 'Tile Fixer',
    ac_repair: 'AC Repair',
    
    // Service Details
    electricianDesc: 'Expert solutions for all your electrical needs — wiring, panel upgrades, lighting, and fault diagnosis.',
    plumberDesc: 'Professional plumbing services for leaks, installations, blockages, and water pressure issues.',
    acFridgeDesc: 'Complete AC and Refrigerator services — installation, deep cleaning, gas refilling, and comprehensive repairs.',
    carpenterDesc: 'Furniture repair, assembly, and custom woodwork from experienced carpenters.',
    painterDesc: 'Fresh coat of paint for your home or office. Quality finish and mess-free service.',
    masonDesc: 'Structural work, bricklaying, and plastering by skilled masons.',
    steelFixerDesc: 'Professional steel reinforcement for slabs, columns, and foundations.',
    labourDesc: 'General manpower for loading, unloading, shifting, and site cleaning.',
    tileFixerDesc: 'Precise tile installation for floors, walls, and bathrooms.',
    
    // Service Features
    faultDiagnosis: 'Fault diagnosis',
    wiringRewiring: 'Wiring & rewiring',
    panelUpgrades: 'Panel upgrades',
    lightFixtures: 'Light fixtures',
    safetyInspections: 'Safety inspections',
    leakRepairs: 'Leak repairs',
    drainCleaning: 'Drain cleaning',
    pipeInstallation: 'Pipe installation',
    waterHeater: 'Water heater',
    tapReplacement: 'Tap replacement',
    deepCleaning: 'Deep cleaning',
    gasRefilling: 'Gas refilling',
    installation: 'Installation',
    fridgeRepair: 'Fridge repair',
    annualService: 'Annual service',
    furnitureRepair: 'Furniture repair',
    doorWindowFix: 'Door/Window fix',
    customWoodwork: 'Custom woodwork',
    lockInstallation: 'Lock installation',
    assembly: 'Assembly',
    interiorPainting: 'Interior painting',
    exteriorPainting: 'Exterior painting',
    wallPutty: 'Wall putty',
    waterproofing: 'Waterproofing',
    stencilWork: 'Stencil work',
    brickwork: 'Brickwork',
    plastering: 'Plastering',
    wallRepair: 'Wall repair',
    concreteWork: 'Concrete work',
    demolition: 'Demolition',
    steelBending: 'Steel bending',
    rebarFixing: 'Rebar fixing',
    slabReinforcement: 'Slab reinforcement',
    meshWork: 'Mesh work',
    welding: 'Welding',
    generalHelp: 'General help',
    loadingUnloading: 'Loading/Unloading',
    debrisRemoval: 'Debris removal',
    siteCleaning: 'Site cleaning',
    packing: 'Packing',
    floorTiling: 'Floor tiling',
    wallTiling: 'Wall tiling',
    grouting: 'Grouting',
    tileReplacement: 'Tile replacement',
    graniteWork: 'Granite work',
    
    // Services Page
    servicesHeader: 'Certified, background-verified professionals ready to solve your home problems.',
    verifiedPros: 'Verified Professionals',
    verifiedProsDesc: 'Every worker is background-checked and ID-verified before onboarding.',
    fastResponse: 'Fast Response',
    fastResponseDesc: 'Average booking-to-assignment time under 30 minutes during business hours.',
    ratedReviewed: 'Rated & Reviewed',
    ratedReviewedDesc: 'Customer reviews after every job keep our quality standards high.',
    bookNow: 'Book Now',
    notSureHeader: 'Not sure what you need?',
    notSureDesc: 'Create a booking and describe your issue — our admin will match you with the right professional.',
    avgTimeLabel: '⏱ Avg Time:',
    ratingLabel: 'Rating',
    
    // About Us Page
    aboutHeroTitle: 'Revolutionizing Local Services',
    aboutHeroSubtitle: 'Service Knock was born with a simple mission: to connect homeowners with the most reliable professionals in their neighborhood through a seamless, digital experience.',
    verifiedWorkers: 'Verified Workers',
    happyCustomers: 'Happy Customers',
    servicesOffered: 'Services Offered',
    citiesCovered: 'Cities Covered',
    ourCoreValues: 'Our Core Values',
    coreValuesSubtitle: 'These principles guide everything we do, from onboarding workers to supporting our customers.',
    trustSafety: 'Trust & Safety',
    trustSafetyDesc: 'Safety is our top priority. Every professional undergoes a multi-step verification process including background checks.',
    qualityService: 'Quality Service',
    qualityServiceDesc: 'We only partner with skilled tradespeople. Our rating system ensures high performance is always rewarded.',
    transparency: 'Transparency',
    transparencyDesc: 'No hidden fees. Upfront estimates and a clear bidding system mean you always know what you are paying for.',
    builtModernHome: 'Built for the Modern Home',
    modernHomeDesc: 'We understand that finding a reliable electrician or plumber can be stressful. That\'s why we\'ve built a platform that removes the friction. With real-time tracking, transparent pricing, and verified reviews, we\'re bringing local services into the 21st century.',
    support247: '24/7 Customer Support',
    securePayments: 'Secure Online Payments',
    qualityGuarantee: 'Quality Guarantee on Jobs',
    
    // Contact Us Page
    contactHeroSubtitle: 'Have questions? We\'re here to help. Reach out to us through any of these channels.',
    callUs: 'Call Us',
    monFri: 'Mon-Fri: 9am - 6pm',
    emailUs: 'Email Us',
    replyWithin24: 'We reply within 24 hours',
    visitUs: 'Visit Us',
    headquarters: 'Headquarters',
    subject: 'Subject',
    howCanWeHelp: 'How can we help?',
    message: 'Message',
    yourMessageHere: 'Your message here...',
    sendMessage: 'Send Message',
    
    // FAQ Page
    faqSubtitle: 'Everything you need to know about Service Knock.',
    stillHaveQuestions: 'Still have questions?',
    supportDesc: 'We\'re here to help. Reach out to our friendly support team.',
    contactSupport: 'Contact Support',
    faqQ1: 'How do I book a service?',
    faqA1: 'To book a service, register as a customer, click on \'Book Now\', select your service type, and describe your issue. Our admin will then match your request with verified professionals who will send you offers.',
    faqQ2: 'How are workers verified?',
    faqA2: 'Every worker on Service Knock undergoes a strict verification process, including ID checks, address verification, and professional certification reviews before they are allowed to accept jobs.',
    faqQ3: 'When do I pay for the service?',
    faqA3: 'You pay once the job is completed and you are satisfied with the work. You can discuss payment methods directly with the professional through our platform.',
    faqQ4: 'What if I\'m not satisfied with the work?',
    faqA4: 'We encourage you to use our review system to rate your experience. If there is a major dispute, you can contact our support team, and we will help mediate the situation.',
    faqQ5: 'Can I cancel a booking?',
    faqA5: 'Yes, you can cancel a booking from your \'My Bookings\' dashboard as long as the work hasn\'t started. Please try to cancel at least 2 hours in advance as a courtesy to the professional.',
    faqQ6: 'How do I become a worker on Service Knock?',
    faqA6: 'You can register as a worker on our registration page. Once you submit your details and certifications, our admin team will review your profile and verify you within 2-3 business days.',
    
    // Dashboards
    myBookingsTitle: 'My Bookings',
    workerDashboard: 'Worker Dashboard',
    totalSpending: 'Total Spending',
    totalEarnings: 'Total Earnings',
    noBookings: 'No bookings found',
    noJobs: 'No jobs found',
    available: 'Available',
    offersSent: 'Offers Sent',
    active: 'Active',
    completed: 'Completed',
    all: 'All',
    pending: 'Pending',
    assigned: 'Assigned',
    accepted: 'Accepted',
    cancelled: 'Cancelled',
    dashboardSubtitle: 'Manage your service requests and active jobs.',
    activeJobs: 'Active Jobs',
    activeJobsDesc: 'Jobs you have accepted — mark them complete when done.',
    noActiveJobs: 'No active jobs',
    noActiveJobsDesc: 'Accept a job from Job Requests to see it here.',
    
    // Booking Card
    jobPrice: 'Job Price',
    worker: 'Worker',
    customer: 'Customer',
    reviews: 'reviews',
    viewImage: 'View Image',
    status: 'Status',
    date: 'Date',
    details: 'Details',
    
    // Auth
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    name: 'Full Name',
    fullName: 'Full Name',
    phone: 'Phone Number',
    registerAs: 'Register As',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: 'Don\'t have an account?',
    forgotPassword: 'Forgot Password?',
    
    // Common
    loading: 'Loading...',
    saving: 'Saving...',
    submitting: 'Submitting...',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    back: 'Back',
    submit: 'Submit',
    availability: 'Availability',
    availableDescription: 'You are currently available for new jobs.',
    unavailableDescription: 'You are currently unavailable.',
    updating: 'Updating...',
    yearsExperience: 'Years of Experience',
    bio: 'Bio',
    bioPlaceholder: 'Tell customers about yourself and your experience...',
    loadingError: 'Failed to load profile.',
    actionFailed: 'Failed to update availability.',
    profileUpdatedToast: 'Profile updated!',
    updateError: 'Failed to update profile.',
    verified: 'Verified',
    unverified: 'Pending Verification',
    viewMore: 'View More',
    search: 'Search',
    address: 'Address',
    description: 'Description',
    title: 'Title',
    
    // My Bookings Dashboard
    viewOffers: 'View Offers',
    edit: 'Edit',
    delete: 'Delete',
    leaveReview: 'Leave Review',
    reviewSubmitted: 'Review Submitted',
    workerOffers: 'Worker Offers',
    noOffersYet: 'No offers received yet. Please wait for workers to respond.',
    acceptOffer: 'Accept Offer',
    accepting: 'Accepting...',
    editJobPost: 'Edit Job Post',
    jobTitle: 'Job Title',
    leaveAReview: 'Leave a Review',
    rating: 'Rating',
    commentOptional: 'Comment (optional)',
    tellUsAboutExperience: 'Tell us about your experience...',
    noBookingsYet: 'You haven\'t made any bookings yet.',
    noFilteredBookings: 'No {status} bookings found.',
    offerAcceptedToast: 'Offer accepted! The worker has been notified.',
    jobDeletedToast: 'Job post deleted.',
    jobUpdatedToast: 'Job updated successfully!',
    reviewSubmittedToast: 'Review submitted! Thank you.',
    
    // Job Requests Dashboard (Worker)
    orCounterOffer: 'Or Counter Offer',
    yourPrice: 'Your Price (Rs.)',
    customPrice: 'Custom price',
    sendCustomOffer: 'Send Custom Offer',
    sending: 'Sending...',
    yourBid: 'Your Bid:',
    waitingForCustomer: 'Waiting for Customer...',
    markCompleted: 'Mark Completed',
    completing: 'Completing...',
    rateCustomer: 'Rate Customer',
    ratedCustomer: 'Rated Customer',
    howWasExperienceWithCustomer: 'How was your experience with this customer?',
    noJobsFound: 'No jobs found',
    noPendingJobsDesc: 'There are no pending jobs for your service type right now.',
    noOffersSentDesc: 'You haven\'t sent any offers yet.',
    noActiveJobsDesc: 'You don\'t have any active jobs.',
    noCompletedJobsDesc: 'No completed jobs yet.',
    offerSentToast: 'Offer sent successfully!',
    jobAcceptedToast: 'Job accepted and added to your active list!',
    jobCompletedToast: 'Job marked as completed!',
    customerReviewToast: 'Review submitted for customer!',
    
    // Book Service Page
    bookServiceSubtitle: 'Fill in the details and we\'ll match you with a verified professional.',
    jobTitlePlaceholder: 'e.g. Fix living room light',
    describeIssue: 'Describe Your Issue',
    issuePlaceholder: 'e.g. My kitchen light keeps flickering...',
    serviceAddress: 'Service Address',
    addressPlaceholder: 'Type your address in Pakistan...',
    jobPhotosOptional: 'Job Photos (Optional)',
    uploadPhoto: 'Upload Photo',
    priceEstimateLabel: 'Price Estimate (Rs.)',
    preferredDateTime: 'Preferred Date/Time',
    submitBooking: 'Submit Booking',
    selectServiceType: 'Please select a service type',
    bookingSubmittedToast: 'Booking submitted! We\'ll assign a worker shortly.',
    suggestionsTitle: 'Suggestions (Pakistan Only)',
    fileTooLarge: 'File too large. Max 5MB allowed.',
    selectService: 'Select Service',
    
    // Profile Page
    editProfile: 'Edit Profile',
    joined: 'Joined',
    userReviews: 'User Reviews',
    noReviewsYet: 'No reviews received yet.',
    untitledService: 'Untitled Service',
    noCommentProvided: 'No comment provided',
    recentJobs: 'Recent Jobs',
    noJobHistory: 'No job history.',
    choosePhoto: 'Choose Photo',
    profileUpdatedToast: 'Profile updated!',
    profileNotFound: 'Profile not found.',
    profilePicture: 'Profile Picture',
    fileTypeLimit: 'PNG, JPG or GIF up to 5MB',
    
    // Home Page
    fastBooking: 'Fast booking in under 60 seconds',
    heroTitleMain: 'Book Trusted Home',
    heroTitleSub: 'Service Professionals',
    verifiedWorkersShort: 'Verified Workers',
    ratedReviewed: 'Rated & Reviewed',
    fastResponse: 'Fast Response',
    howItWorks: 'How It Works',
    threeSteps: '3 simple steps to get your issue resolved',
    whatCustomersSay: 'What Customers Say',
    trustedHomeowners: 'Trusted by thousands of homeowners',
    readyToStart: 'Ready to get started?',
    ctaBannerDesc: 'Join thousands of happy customers. Book your first service in under 60 seconds.',
    pickAService: 'Pick a Service',
    pickAServiceDesc: 'Choose from Electrician, Plumber, AC Technician, or Carpenter.',
    submitRequest: 'Submit Request',
    submitRequestDesc: 'Describe your issue and add your address in seconds.',
    jobDone: 'Job Done',
    jobDoneDesc: 'Worker arrives, completes the job, you rate them.',
    happyCustomersLabel: 'Happy Customers',
    jobsCompletedLabel: 'Jobs Completed',
    avgRatingLabel: 'Average Rating',
    satisfactionRateLabel: 'Satisfaction Rate',
    saraKhan: 'Sara Khan',
    homeowner: 'Homeowner',
    saraTestimonial: 'The electrician from Service Knock arrived in under 2 hours. He was super professional and fixed my wiring issues perfectly!',
    aliHaider: 'Ali Haider',
    businessOwner: 'Business Owner',
    aliTestimonial: 'Used Service Knock for our office AC repair. The service was fast, affordable, and the worker was verified. Highly recommend.',
    asimIqbal: 'Asim Iqbal',
    apartmentTenant: 'Apartment Tenant',
    asimTestimonial: 'Booked a plumber from Service Knock at 9pm and had it sorted by morning. Amazing speed and quality service for our family.',
    bilalSiddiqui: 'Bilal Siddiqui',
    interiorDesigner: 'Interior Designer',
    bilalTestimonial: 'Found a great carpenter through Service Knock to fix my kitchen cabinets. Exceptional quality and very reasonable pricing.',
    maryamJaved: 'Maryam Javed',
    doctor: 'Doctor',
    maryamTestimonial: 'Service Knock is my go-to for any home repairs. Their workers are punctual, skilled, and the booking process is extremely smooth.',
    zainabRaza: 'Zainab Raza',
    teacher: 'Teacher',
    zainabTestimonial: 'Extremely satisfied with the plumber from Service Knock. He diagnosed the leak quickly and fixed it without any mess or hassle.',
    
    // Financials
    spendingTotal: 'Total Spending',
    earningsTotal: 'Total Earnings',
    urduNameLabel: 'Name in Urdu',
    
    // Privacy Policy
    privacyTitle: 'Privacy Policy',
    lastUpdated: 'Last Updated: May 2026',
    infoCollect: '1. Information We Collect',
    infoCollectDesc: 'When you use Service Knock, we collect personal information that you provide to us, such as your name, email address, phone number, and location. For professionals, we also collect professional certifications and identification documents.',
    accountInfo: 'Account Information: Name, email, phone number, password.',
    bookingData: 'Booking Data: Service descriptions, addresses, scheduled times.',
    paymentData: 'Payment Data: We use secure third-party processors and do not store full card details.',
    howWeUse: '2. How We Use Your Information',
    howWeUseDesc: 'We use your data to facilitate the booking process, verify identities, process payments, and improve our services. Specifically:',
    connectCustomers: 'Connecting customers with service providers.',
    sendNotifications: 'Sending notification alerts about booking status.',
    customerSupport: 'Customer support and dispute resolution.',
    platformAnalytics: 'Platform analytics to improve user experience.',
    dataSecurity: '3. Data Security',
    dataSecurityDesc: 'We implement a variety of security measures to maintain the safety of your personal information. Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems.',
    sharingThirdParties: '4. Sharing with Third Parties',
    sharingThirdPartiesDesc: 'We share your contact details with the service provider only after you have accepted an offer, as required to fulfill the service request. We do not sell your personal data to third parties for marketing purposes.',
    yourRights: '5. Your Rights',
    yourRightsDesc: 'You have the right to access, correct, or delete your personal information at any time through your account settings or by contacting our support team.',
    
    // Terms & Conditions
    termsTitle: 'Terms & Conditions',
    acceptanceTerms: '1. Acceptance of Terms',
    acceptanceTermsDesc: 'By accessing and using Service Knock, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use our platform.',
    userAccounts: '2. User Accounts',
    userAccountsDesc: 'You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate and complete information during registration. Service Knock reserves the right to suspend accounts that provide false information.',
    bookingPayments: '3. Booking and Payments',
    bookingPaymentsDesc: 'Customers agree to pay the price accepted in the offer system. Payments should be made through the agreed-upon methods. Service Knock acts as a marketplace and is not responsible for disputes regarding the quality of work, though we will provide assistance in resolution.',
    cancellationsTerms: '4. Cancellations',
    cancellationsTermsDesc: 'Cancellations may be subject to fees if made within a certain timeframe of the scheduled appointment. Please refer to individual service provider terms for specific cancellation policies.',
    proVerification: '5. Professional Verification',
    proVerificationDesc: 'While Service Knock performs background checks, customers are encouraged to use their judgment and read reviews before accepting offers.',
    liabilityLimitation: '6. Limitation of Liability',
    liabilityLimitationDesc: 'Service Knock shall not be liable for any indirect, incidental, or consequential damages resulting from the use of our services or the actions of independent contractors hired through the platform.',
    voiceDescription: 'Voice Description',
    speakIssue: 'Speak Issue',
    stopRecording: 'Stop Recording',
    recordingStarted: 'Recording started...',
    recordingStopped: 'Recording stopped.',
    micError: 'Microphone access denied.',
    blockedAccountAlert: 'Your account is blocked please contact support for details.',
    reportProfile: 'Report Profile',
    reported: 'Reported',
    confirmReport: 'Are you sure you want to report this profile? Multiple reports will lead to automatic account block.',
    verified: 'Verified',
    unverified: 'Unverified',
    identityVerification: 'Identity Verification',
    verifyIdentityDesc: 'Verify your identity by uploading a clear photo of your CNIC. This builds trust in the community.',
    uploadCNIC: 'Upload CNIC Photo',
    verificationPending: 'Verification Pending',
    verificationPendingDesc: 'Your ID is being reviewed by our team. This usually takes 24 hours.',
    verificationRejected: 'Verification Rejected',
    verificationRejectedReason: 'Reason:',
    resubmitID: 'Resubmit ID',
    submitForVerification: 'Submit for Verification',
    verificationSuccess: 'Verification submitted successfully!',
  },
  ur: {
    // Navbar
    home: 'ہوم',
    services: 'خدمات',
    about: 'ہمارے بارے میں',
    contact: 'رابطہ کریں',
    login: 'لاگ ان',
    getStarted: 'شروع کریں',
    myProfile: 'میری پروفائل',
    signOut: 'سائن آؤٹ',
    adminPanel: 'ایڈمن پینل',
    bookService: 'سروس بک کریں',
    myBookings: 'میری بکنگز',
    jobRequests: 'کام کی درخواستیں',
    dashboard: 'ڈیش بورڈ',
    workers: 'ورکرز',
    support: 'سپورٹ',
    aboutUs: 'ہمارے بارے میں',
    contactUs: 'رابطہ کریں',
    faqs: 'عام سوالات',
    bookings: 'بکنگز',
    jobs: 'کام',
    book: 'بک کریں',
    profile: 'پروفائل',
    ourBlog: 'ہمارا بلاگ',
    privacyPolicy: 'پرائیویسی پالیسی',
    termsConditions: 'شرائط و ضوابط',
    newsletter: 'نیوز لیٹر',
    newsletterPlaceholder: 'آپ کا ای میل',
    allRightsReserved: 'تمام حقوق محفوظ ہیں۔',
    footerDesc: 'سروس ناک آپ کا بہترین مقامی سروس بکنگ پلیٹ فارم ہے، جو آپ کو آپ کے علاقے میں انتہائی ماہر اور قابل اعتماد پیشہ ور افراد سے جوڑنے کے لیے وقف ہے۔ ہم آپ کے گھر اور کاروبار کی تمام ضروریات کے لیے قابل اعتماد حل فراہم کرتے ہیں، اس بات کو یقینی بناتے ہوئے کہ معیاری سروس صرف چند کلکس کے فاصلے پر ہو۔',
    addressFull: '123 سروس لین، ٹیک سٹی، 10001',

    // Hero Section
    heroTitle: 'پیشہ ورانہ گھریلو خدمات آپ کی دہلیز پر',
    heroSubtitle: 'صرف چند کلکس میں بھروسہ مند الیکٹریشن، پلمبر، پینٹر اور بہت کچھ بک کریں۔ ہر گھر کی ضرورت کے لیے قابل اعتماد مدد۔',
    heroCTA: 'ابھی سروس بک کریں',
    activePros: 'فعال پیشہ ور افراد',
    trustedUsers: 'بھروسہ مند صارفین',
    
    // Services Section
    ourServices: 'ہماری خدمات',
    servicesSubtitle: 'ہم آپ کی روزمرہ کی ضروریات میں مدد کے لیے پیشہ ورانہ گھریلو خدمات کی ایک وسیع رینج فراہم کرتے ہیں۔',
    electrician: 'الیکٹریشن',
    plumber: 'پلمبر',
    ac_fridge_repair: 'اے سی / فریج کی مرمت',
    carpenter: 'بڑھئی',
    painter: 'پینٹر',
    mason: 'راج مستری',
    steel_fixer: 'سٹیل فکسر',
    labour: 'مزدور',
    tile_fixer: 'ٹائل فکسر',
    ac_repair: 'اے سی کی مرمت',
    irfanRashid: 'عرفان رشید',
    irfanrashid: 'عرفان رشید',
    'Irfan Rashid': 'عرفان رشید',
    khurshidAhmedKhan: 'خورشید احمد خان',
    'Khurshid Ahmed Khan': 'خورشید احمد خان',
    serviceTapAdmin: 'سروس ٹیپ ایڈمن',
    serviceKnockAdmin: 'سروس ناک ایڈمن',
    faizanTraders: 'فیضان ٹریڈرز',
    'Faizan Traders': 'فیضان ٹریڈرز',
    faizan: 'فیضان',
    traders: 'ٹریڈرز',
    abdulRaheemSufi: 'عبدالرحیم صوفی',
    'Abdul Raheem Sufi': 'عبدالرحیم صوفی',
    abdul: 'عبدال',
    raheem: 'رحیم',
    sufi: 'صوفی',
    irfan: 'عرفان',
    rashid: 'رشید',
    ali: 'علی',
    haider: 'حیدر',
    asim: 'عاصم',
    iqbal: 'اقبال',
    bilal: 'بلال',
    siddiqui: 'صدیقی',
    maryam: 'مریم',
    javed: 'جاوید',
    zainab: 'زینب',
    raza: 'رضا',
    sara: 'سارہ',
    khan: 'خان',

    // Service Details
    electricianDesc: 'آپ کی تمام برقی ضروریات کے لیے ماہرانہ حل — وائرنگ، پینل اپ گریڈ، لائٹنگ، اور خرابی کی تشخیص۔',
    plumberDesc: 'لیک، انسٹالیشن، بلاکج، اور پانی کے پریشر کے مسائل کے لیے پیشہ ورانہ پلمبنگ سروسز۔',
    acFridgeDesc: 'مکمل اے سی اور ریفریجریٹر سروسز — انسٹالیشن، گہری صفائی، گیس ری فلنگ، اور جامع مرمت۔',
    carpenterDesc: 'تجربہ کار بڑھئیوں سے فرنیچر کی مرمت، اسمبلی، اور کسٹم لکڑی کا کام۔',
    painterDesc: 'آپ کے گھر یا دفتر کے لیے پینٹ کا نیا کوٹ۔ معیاری فنش اور گندگی سے پاک سروس۔',
    masonDesc: 'ماہر راج مستریوں کے ذریعے تعمیراتی کام، اینٹوں کی چنائی، اور پلستر۔',
    steelFixerDesc: 'سلیب، کالموں اور بنیادوں کے لیے پیشہ ورانہ سٹیل کی مضبوطی۔',
    labourDesc: 'لوڈنگ، ان لوڈنگ، شفٹنگ، اور سائٹ کی صفائی کے لیے عام افرادی قوت۔',
    tileFixerDesc: 'فرش، دیواروں اور باتھ رومز کے لیے درست ٹائل انسٹالیشن۔',
    
    // Service Features
    faultDiagnosis: 'خرابی کی تشخیص',
    wiringRewiring: 'وائرنگ اور ری وائرنگ',
    panelUpgrades: 'پینل اپ گریڈ',
    lightFixtures: 'لائٹ فکسچر',
    safetyInspections: 'حفاظتی معائنہ',
    leakRepairs: 'لیک کی مرمت',
    drainCleaning: 'ڈرین کی صفائی',
    pipeInstallation: 'پائپ کی تنصیب',
    waterHeater: 'واٹر ہیٹر',
    tapReplacement: 'نل کی تبدیلی',
    deepCleaning: 'گہری صفائی',
    gasRefilling: 'گیس ری فلنگ',
    installation: 'انسٹالیشن',
    fridgeRepair: 'فریج کی مرمت',
    annualService: 'سالانہ سروس',
    furnitureRepair: 'فرنیچر کی مرمت',
    doorWindowFix: 'دروازہ/کھڑکی کی مرمت',
    customWoodwork: 'کسٹم لکڑی کا کام',
    lockInstallation: 'لاک کی تنصیب',
    assembly: 'اسمبلی',
    interiorPainting: 'اندرونی پینٹنگ',
    exteriorPainting: 'بیرونی پینٹنگ',
    wallPutty: 'وال پٹی',
    waterproofing: 'واٹر پروفنگ',
    stencilWork: 'سٹینسل ورک',
    brickwork: 'اینٹوں کا کام',
    plastering: 'پلستر',
    wallRepair: 'دیوار کی مرمت',
    concreteWork: 'کنکریٹ کا کام',
    demolition: 'انہدام',
    steelBending: 'سٹیل موڑنا',
    rebarFixing: 'ریبار فکسنگ',
    slabReinforcement: 'سلیب کی مضبوطی',
    meshWork: 'میش ورک',
    welding: 'ویلڈنگ',
    generalHelp: 'عام مدد',
    loadingUnloading: 'لوڈنگ/ان لوڈنگ',
    debrisRemoval: 'ملبہ ہٹانا',
    siteCleaning: 'سائٹ کی صفائی',
    packing: 'پیکنگ',
    floorTiling: 'فرش کی ٹائلیں',
    wallTiling: 'دیوار کی ٹائلیں',
    grouting: 'گراؤٹنگ',
    tileReplacement: 'ٹائل کی تبدیلی',
    graniteWork: 'گرینائٹ کا کام',

    // Services Page
    servicesHeader: 'تصدیق شدہ، بیک گراؤنڈ سے تصدیق شدہ پیشہ ور افراد آپ کے گھر کے مسائل حل کرنے کے لیے تیار ہیں۔',
    verifiedPros: 'تصدیق شدہ پیشہ ور افراد',
    verifiedProsDesc: 'آن بورڈنگ سے پہلے ہر ورکر کا بیک گراؤنڈ اور شناختی کارڈ چیک کیا جاتا ہے۔',
    fastResponse: 'تیز ردعمل',
    fastResponseDesc: 'کاروباری اوقات کے دوران اوسط بکنگ سے اسائنمنٹ کا وقت 30 منٹ سے کم ہے۔',
    ratedReviewed: 'درجہ بندی اور جائزہ',
    ratedReviewedDesc: 'ہر کام کے بعد کسٹمر کے جائزے ہمارے معیار کو برقرار رکھتے ہیں۔',
    bookNow: 'ابھی بک کریں',
    notSureHeader: 'پتہ نہیں آپ کو کیا چاہیے؟',
    notSureDesc: 'بکنگ بنائیں اور اپنے مسئلے کی وضاحت کریں — ہمارا ایڈمن آپ کو صحیح پیشہ ور سے ملا دے گا۔',
    avgTimeLabel: '⏱ اوسط وقت:',
    ratingLabel: 'درجہ بندی',

    // About Us Page
    aboutHeroTitle: 'مقامی خدمات میں انقلاب لانا',
    aboutHeroSubtitle: 'سروس ناک ایک سادہ مشن کے ساتھ پیدا ہوا تھا: گھر کے مالکان کو ایک ہموار، ڈیجیٹل تجربے کے ذریعے ان کے پڑوس کے سب سے زیادہ قابل اعتماد پیشہ ور افراد کے ساتھ جوڑنا۔',
    verifiedWorkers: 'تصدیق شدہ ورکرز',
    happyCustomers: 'خوش حال صارفین',
    servicesOffered: 'پیش کردہ خدمات',
    citiesCovered: 'شامل شہر',
    ourCoreValues: 'ہماری بنیادی اقدار',
    coreValuesSubtitle: 'یہ اصول ہمارے ہر کام میں ہماری رہنمائی کرتے ہیں، ورکرز کی بھرتی سے لے کر اپنے صارفین کی مدد تک۔',
    trustSafety: 'بھروسہ اور حفاظت',
    trustSafetyDesc: 'حفاظت ہماری اولین ترجیح ہے۔ ہر پیشہ ور بیک گراؤنڈ چیک سمیت متعدد مراحل کے تصدیقی عمل سے گزرتا ہے۔',
    qualityService: 'معیاری سروس',
    qualityServiceDesc: 'ہم صرف ماہر کاریگروں کے ساتھ شراکت داری کرتے ہیں۔ ہمارا ریٹنگ سسٹم اس بات کو یقینی بناتا ہے کہ اچھی کارکردگی کا ہمیشہ صلہ ملے۔',
    transparency: 'شفافیت',
    transparencyDesc: 'کوئی پوشیدہ فیس نہیں۔ پہلے سے تخمینہ اور واضح بولی لگانے کا نظام مطلب ہے کہ آپ ہمیشہ جانتے ہیں کہ آپ کس چیز کی ادائیگی کر رہے ہیں۔',
    builtModernHome: 'جدید گھر کے لیے تیار',
    modernHomeDesc: 'ہم سمجھتے ہیں کہ قابل اعتماد الیکٹریشن یا پلمبر تلاش کرنا مشکل ہو سکتا ہے۔ اسی لیے ہم نے ایک ایسا پلیٹ فارم بنایا ہے جو اس مشکل کو ختم کرتا ہے۔ ریئل ٹائم ٹریکنگ، شفاف قیمتوں اور تصدیق شدہ جائزوں کے ساتھ، ہم مقامی خدمات کو 21 ویں صدی میں لے جا رہے ہیں۔',
    support247: '24/7 کسٹمر سپورٹ',
    securePayments: 'محفوظ آن لائن ادائیگیاں',
    qualityGuarantee: 'کام پر معیار کی ضمانت',

    // Contact Us Page
    contactHeroSubtitle: 'سوالات ہیں؟ ہم مدد کے لیے حاضر ہیں۔ ان میں سے کسی بھی چینل کے ذریعے ہم سے رابطہ کریں۔',
    callUs: 'ہمیں کال کریں',
    monFri: 'پیر تا جمعہ: صبح 9 بجے سے شام 6 بجے تک',
    emailUs: 'ہمیں ای میل کریں',
    replyWithin24: 'ہم 24 گھنٹوں کے اندر جواب دیتے ہیں',
    visitUs: 'ہمارے ہاں تشریف لائیں',
    headquarters: 'ہیڈ کوارٹر',
    subject: 'موضوع',
    howCanWeHelp: 'ہم آپ کی کیا مدد کر سکتے ہیں؟',
    message: 'پیغام',
    yourMessageHere: 'آپ کا پیغام یہاں...',
    sendMessage: 'پیغام بھیجیں',

    // FAQ Page
    faqSubtitle: 'سروس ناک کے بارے میں ہر وہ چیز جو آپ کو جاننے کی ضرورت ہے۔',
    stillHaveQuestions: 'اب بھی سوالات ہیں؟',
    supportDesc: 'ہم مدد کے لیے حاضر ہیں۔ ہماری دوستانہ سپورٹ ٹیم سے رابطہ کریں۔',
    contactSupport: 'سپورٹ سے رابطہ کریں',
    faqQ1: 'میں سروس کیسے بک کروں؟',
    faqA1: 'سروس بک کرنے کے لیے، بطور گاہک رجسٹر ہوں، \'ابھی بک کریں\' پر کلک کریں، اپنی سروس کی قسم منتخب کریں، اور اپنے مسئلے کی وضاحت کریں۔ اس کے بعد ہمارا ایڈمن آپ کی درخواست کو تصدیق شدہ پیشہ ور افراد سے ملا دے گا جو آپ کو آفرز بھیجیں گے۔',
    faqQ2: 'ورکرز کی تصدیق کیسے کی جاتی ہے؟',
    faqA2: 'سروس ناک پر ہر ورکر ایک سخت تصدیقی عمل سے گزرتا ہے، بشمول شناختی کارڈ کی جانچ، پتے کی تصدیق، اور پیشہ ورانہ سرٹیفیکیشن کا جائزہ لینے سے پہلے کہ انہیں کام قبول کرنے کی اجازت دی جائے۔',
    faqQ3: 'میں سروس کے لیے کب ادائیگی کروں؟',
    faqA3: 'آپ کام مکمل ہونے اور کام سے مطمئن ہونے کے بعد ادائیگی کرتے ہیں۔ آپ ہمارے پلیٹ فارم کے ذریعے پیشہ ور افراد کے ساتھ براہ راست ادائیگی کے طریقوں پر تبادلہ خیال کر سکتے ہیں۔',
    faqQ4: 'اگر میں کام سے مطمئن نہ ہوں تو کیا ہوگا؟',
    faqA4: 'ہم آپ کو اپنے تجربے کی درجہ بندی کرنے کے لیے ہمارے ریویو سسٹم کو استعمال کرنے کی ترغیب دیتے ہیں۔ اگر کوئی بڑا تنازعہ ہے تو، آپ ہماری سپورٹ ٹیم سے رابطہ کر سکتے ہیں، اور ہم صورتحال کو حل کرنے میں مدد کریں گے۔',
    faqQ5: 'کیا میں بکنگ منسوخ کر سکتا ہوں؟',
    faqA5: 'جی ہاں، آپ اپنے \'میری بکنگز\' ڈیش بورڈ سے بکنگ منسوخ کر سکتے ہیں جب تک کہ کام شروع نہ ہوا ہو۔ براہ کرم پیشہ ور افراد کے احترام میں کم از کم 2 گھنٹے پہلے منسوخ کرنے کی کوشش کریں۔',
    faqQ6: 'میں سروس ناک پر ورکر کیسے بن سکتا ہوں؟',
    faqA6: 'آپ ہمارے رجسٹریشن پیج پر بطور ورکر رجسٹر ہو سکتے ہیں۔ ایک بار جب آپ اپنی تفصیلات اور سرٹیفیکیشن جمع کروا دیں گے، ہماری ایڈمن ٹیم آپ کی پروفائل کا جائزہ لے گی اور 2-3 کاروباری دنوں میں آپ کی تصدیق کر دے گی۔',

    // Dashboards
    myBookingsTitle: 'میری بکنگز',
    workerDashboard: 'ورکر ڈیش بورڈ',
    totalSpending: 'کل خرچ',
    totalEarnings: 'کل آمدنی',
    noBookings: 'کوئی بکنگ نہیں ملی',
    noJobs: 'کوئی کام نہیں ملا',
    available: 'دستیاب',
    offersSent: 'بھیجی گئی پیشکشیں',
    active: 'فعال',
    completed: 'مکمل',
    all: 'تمام',
    pending: 'زیر التواء',
    assigned: 'نامزد',
    accepted: 'قبول شدہ',
    cancelled: 'منسوخ',
    dashboardSubtitle: 'اپنی سروس کی درخواستوں اور فعال کاموں کا انتظام کریں۔',
    activeJobs: 'فعال کام',
    activeJobsDesc: 'وہ کام جو آپ نے قبول کیے ہیں — مکمل ہونے پر انہیں مکمل نشان زد کریں۔',
    noActiveJobs: 'کوئی فعال کام نہیں ہے',
    noActiveJobsDesc: 'یہاں دیکھنے کے لیے جاب ریکویسٹ سے کوئی کام قبول کریں۔',
    
    // Booking Card
    jobPrice: 'کام کی قیمت',
    worker: 'ورکر',
    customer: 'گاہک',
    reviews: 'تبصرے',
    viewImage: 'تصویر دیکھیں',
    status: 'صورتحال',
    date: 'تاریخ',
    details: 'تفصیلات',
    
    // Auth
    welcomeBack: 'خوش آمدید',
    createAccount: 'اکاؤنٹ بنائیں',
    email: 'ای میل ایڈریس',
    password: 'پاس ورڈ',
    name: 'پورا نام',
    fullName: 'پورا نام',
    phone: 'فون نمبر',
    registerAs: 'بطور رجسٹر ہوں',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    forgotPassword: 'پاس ورڈ بھول گئے؟',
    
    // Common
    loading: 'لوڈ ہو رہا ہے...',
    saving: 'محفوظ ہو رہا ہے...',
    submitting: 'جمع ہو رہا ہے...',
    cancel: 'منسوخ کریں',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    back: 'واپس',
    submit: 'جمع کرائیں',
    availability: 'دستیابی',
    availableDescription: 'آپ فی حال نئے کاموں کے لیے دستیاب ہیں۔',
    unavailableDescription: 'آپ فی حال دستیاب نہیں ہیں۔',
    updating: 'اپ ڈیٹ ہو رہا ہے...',
    yearsExperience: 'تجربے کے سال',
    bio: 'تعارف',
    bioPlaceholder: 'صارفین کو اپنے اور اپنے تجربے کے بارے میں بتائیں...',
    loadingError: 'پروفائل لوڈ کرنے میں ناکامی۔',
    actionFailed: 'دستیابی اپ ڈیٹ کرنے میں ناکامی۔',
    profileUpdatedToast: 'پروفائل اپ ڈیٹ ہو گیا!',
    updateError: 'پروفائل اپ ڈیٹ کرنے میں ناکامی۔',
    verified: 'تصدیق شدہ',
    unverified: 'تصدیق زیر التواء',
    viewMore: 'مزید دیکھیں',
    search: 'تلاش کریں',
    address: 'پتہ',
    description: 'تفصیل',
    title: 'عنوان',

    // My Bookings Dashboard
    viewOffers: 'آفرز دیکھیں',
    edit: 'ترمیم کریں',
    delete: 'حذف کریں',
    leaveReview: 'ریویو دیں',
    reviewSubmitted: 'ریویو جمع کر دیا گیا',
    workerOffers: 'ورکر کی آفرز',
    noOffersYet: 'ابھی تک کوئی آفر موصول نہیں ہوئی۔ براہ کرم ورکرز کے جواب کا انتظار کریں۔',
    acceptOffer: 'آفر قبول کریں',
    accepting: 'قبول ہو رہا ہے...',
    editJobPost: 'کام کی پوسٹ میں ترمیم کریں',
    jobTitle: 'کام کا عنوان',
    leaveAReview: 'ریویو دیں',
    rating: 'درجہ بندی',
    commentOptional: 'تبصرہ (اختیاری)',
    tellUsAboutExperience: 'ہمیں اپنے تجربے کے بارے میں بتائیں...',
    noBookingsYet: 'آپ نے ابھی تک کوئی بکنگ نہیں کی ہے۔',
    noFilteredBookings: 'کوئی {status} بکنگ نہیں ملی۔',
    offerAcceptedToast: 'آفر قبول کر لی گئی! ورکر کو مطلع کر دیا گیا ہے۔',
    jobDeletedToast: 'کام کی پوسٹ حذف کر دی گئی۔',
    jobUpdatedToast: 'کام کی پوسٹ کامیابی کے ساتھ اپ ڈیٹ ہو گئی!',
    reviewSubmittedToast: 'ریویو جمع ہو گیا! شکریہ۔',

    // Job Requests Dashboard (Worker)
    orCounterOffer: 'یا اپنی پیشکش دیں',
    yourPrice: 'آپ کی قیمت (روپے)',
    customPrice: 'اپنی قیمت',
    sendCustomOffer: 'اپنی آفر بھیجیں',
    sending: 'بھیجی جا رہی ہے...',
    yourBid: 'آپ کی بولی:',
    waitingForCustomer: 'گاہک کا انتظار ہے...',
    markCompleted: 'مکمل قرار دیں',
    completing: 'مکمل ہو رہا ہے...',
    rateCustomer: 'گاہک کی درجہ بندی کریں',
    ratedCustomer: 'گاہک کی درجہ بندی کر دی گئی',
    howWasExperienceWithCustomer: 'اس گاہک کے ساتھ آپ کا تجربہ کیسا رہا؟',
    noJobsFound: 'کوئی کام نہیں ملا',
    noPendingJobsDesc: 'اس وقت آپ کی سروس کی قسم کے لیے کوئی زیر التواء کام نہیں ہے۔',
    noOffersSentDesc: 'آپ نے ابھی تک کوئی آفر نہیں بھیجی ہے۔',
    noActiveJobsDesc: 'آپ کا کوئی فعال کام نہیں ہے۔',
    noCompletedJobsDesc: 'ابھی تک کوئی مکمل شدہ کام نہیں ہے۔',
    offerSentToast: 'آفر کامیابی کے ساتھ بھیج دی گئی!',
    jobAcceptedToast: 'کام قبول کر لیا گیا اور آپ کی فعال فہرست میں شامل کر دیا گیا!',
    jobCompletedToast: 'کام مکمل قرار دے دیا گیا!',
    customerReviewToast: 'گاہک کے لیے ریویو جمع کر دیا گیا!',

    // Book Service Page
    bookServiceSubtitle: 'تفصیلات پُر کریں اور ہم آپ کو ایک تصدیق شدہ پیشہ ور سے ملا دیں گے۔',
    jobTitlePlaceholder: 'مثال کے طور پر: ڈرائنگ روم کی لائٹ ٹھیک کرنی ہے',
    describeIssue: 'اپنے مسئلے کی وضاحت کریں',
    issuePlaceholder: 'مثال کے طور پر: میرے باورچی خانے کی لائٹ ٹمٹما رہی ہے...',
    serviceAddress: 'سروس کا پتہ',
    addressPlaceholder: 'پاکستان میں اپنا پتہ لکھیں...',
    jobPhotosOptional: 'کام کی تصاویر (اختیاری)',
    uploadPhoto: 'تصویر اپ لوڈ کریں',
    priceEstimateLabel: 'قیمت کا تخمینہ (روپے)',
    preferredDateTime: 'پسندیدہ تاریخ اور وقت',
    submitBooking: 'بکنگ جمع کروائیں',
    selectServiceType: 'براہ کرم سروس کی قسم منتخب کریں',
    bookingSubmittedToast: 'بکنگ جمع ہو گئی! ہم جلد ہی ایک ورکر مقرر کریں گے۔',
    suggestionsTitle: 'تجاویز (صرف پاکستان)',
    fileTooLarge: 'فائل بہت بڑی ہے۔ زیادہ سے زیادہ 5MB کی اجازت ہے۔',
    selectService: 'سروس منتخب کریں',

    // Profile Page
    editProfile: 'پروفائل میں ترمیم کریں',
    joined: 'شامل ہوئے',
    userReviews: 'صارفین کے ریویوز',
    noReviewsYet: 'ابھی تک کوئی ریویو موصول نہیں ہوا۔',
    untitledService: 'بغیر عنوان کے سروس',
    noCommentProvided: 'کوئی تبصرہ نہیں کیا گیا',
    recentJobs: 'حالیہ کام',
    noJobHistory: 'کام کی کوئی ہسٹری نہیں ہے۔',
    choosePhoto: 'تصویر منتخب کریں',
    profileUpdatedToast: 'پروفائل اپ ڈیٹ ہو گئی!',
    profileNotFound: 'پروفائل نہیں ملی۔',
    profilePicture: 'پروفائل تصویر',
    fileTypeLimit: 'PNG, JPG یا GIF، زیادہ سے زیادہ 5MB',

    // Home Page
    fastBooking: '60 سیکنڈ سے کم میں فاسٹ بکنگ',
    heroTitleMain: 'بھروسہ مند گھریلو',
    heroTitleSub: 'پیشہ ور افراد بک کریں',
    verifiedWorkersShort: 'تصدیق شدہ ورکرز',
    ratedReviewed: 'ریٹیڈ اور ریویوڈ',
    fastResponse: 'فوری رسپانس',
    howItWorks: 'یہ کیسے کام کرتا ہے',
    threeSteps: 'آپ کے مسئلے کو حل کرنے کے لیے 3 آسان اقدامات',
    whatCustomersSay: 'گاہک کیا کہتے ہیں',
    trustedHomeowners: 'ہزاروں گھر مالکان کا بھروسہ',
    readyToStart: 'شروع کرنے کے لیے تیار ہیں؟',
    ctaBannerDesc: 'ہزاروں خوش کن صارفین میں شامل ہوں۔ اپنی پہلی سروس 60 سیکنڈ سے کم میں بک کریں۔',
    pickAService: 'سروس کا انتخاب کریں',
    pickAServiceDesc: 'الیکٹریشن، پلمبر، اے سی ٹیکنیشن، یا بڑھئی میں سے انتخاب کریں۔',
    submitRequest: 'درخواست جمع کریں',
    submitRequestDesc: 'اپنے مسئلے کی وضاحت کریں اور سیکنڈوں میں اپنا پتہ شامل کریں۔',
    jobDone: 'کام مکمل',
    jobDoneDesc: 'ورکر آتا ہے، کام مکمل کرتا ہے، آپ انہیں ریٹ کرتے ہیں۔',
    happyCustomersLabel: 'خوش گاہک',
    jobsCompletedLabel: 'مکمل کام',
    avgRatingLabel: 'اوسط ریٹنگ',
    satisfactionRateLabel: 'اطمینان کی شرح',
    saraKhan: 'سارہ خان',
    homeowner: 'گھر کی مالک',
    saraTestimonial: 'سروس ناک کا الیکٹریشن 2 گھنٹے سے بھی کم وقت میں پہنچ گیا۔ انتہائی پیشہ ورانہ اور ہر چیز کو مکمل طور پر ٹھیک کر دیا!',
    aliHaider: 'علی حیدر',
    businessOwner: 'کاروبار کا مالک',
    aliTestimonial: 'ہمارے دفتر کے اے سی کی مرمت کے لیے سروس ناک کا استعمال کیا۔ تیز، سستا، اور ورکر تصدیق شدہ تھا۔ پرزور سفارش کرتا ہوں۔',
    asimIqbal: 'عاصم اقبال',
    apartmentTenant: 'اپارٹمنٹ کرایہ دار',
    asimTestimonial: 'رات 9 بجے سروس ناک سے پلمبر بک کیا اور صبح تک سب ٹھیک ہو گیا۔ ہمارے خاندان کے لیے حیرت انگیز رفتار اور معیار!',
    bilalSiddiqui: 'بلال صدیقی',
    interiorDesigner: 'انٹیریئر ڈیزائنر',
    bilalTestimonial: 'باورچی خانے کی الماریاں ٹھیک کرنے کے لیے سروس ناک سے بڑھئی ملا۔ غیر معمولی معیار اور بہت مناسب قیمت۔',
    maryamJaved: 'مریم جاوید',
    doctor: 'ڈاکٹر',
    maryamTestimonial: 'سروس ناک گھر کی کسی بھی مرمت کے لیے میری پہلی پسند ہے۔ ان کے ورکرز وقت کے پابند، ماہر اور بکنگ کا عمل بہت آسان ہے۔',
    zainabRaza: 'زینب رضا',
    teacher: 'استانی',
    zainabTestimonial: 'سروس ناک کے پلمبر سے انتہائی مطمئن ہوں۔ اس نے لیک کی جلد تشخیص کی اور بغیر کسی پریشانی کے اسے ٹھیک کر دیا۔',
    
    // Financials
    spendingTotal: 'کل خرچ',
    earningsTotal: 'کل آمدنی',
    urduNameLabel: 'اردو میں نام',

    // Privacy Policy
    privacyTitle: 'پرائیویسی پالیسی',
    lastUpdated: 'آخری بار اپ ڈیٹ کیا گیا: مئی 2026',
    infoCollect: '1. معلومات جو ہم جمع کرتے ہیں',
    infoCollectDesc: 'جب آپ سروس ناک استعمال کرتے ہیں، تو ہم وہ ذاتی معلومات جمع کرتے ہیں جو آپ ہمیں فراہم کرتے ہیں، جیسے آپ کا نام، ای میل پتہ، فون نمبر، اور مقام۔ پیشہ ور افراد کے لیے، ہم پیشہ ورانہ سرٹیفیکیشن اور شناختی دستاویزات بھی جمع کرتے ہیں۔',
    accountInfo: 'اکاؤنٹ کی معلومات: نام، ای میل، فون نمبر، پاس ورڈ۔',
    bookingData: 'بکنگ ڈیٹا: سروس کی تفصیل، پتے، طے شدہ اوقات۔',
    paymentData: 'ادائیگی کا ڈیٹا: ہم محفوظ تھرڈ پارٹی پروسیسرز استعمال کرتے ہیں اور مکمل کارڈ کی تفصیلات محفوظ نہیں کرتے۔',
    howWeUse: '2. ہم آپ کی معلومات کیسے استعمال کرتے ہیں',
    howWeUseDesc: 'ہم آپ کا ڈیٹا بکنگ کے عمل کو آسان بنانے، شناخت کی تصدیق کرنے، ادائیگیوں پر کارروائی کرنے اور اپنی خدمات کو بہتر بنانے کے لیے استعمال کرتے ہیں۔ خاص طور پر:',
    connectCustomers: 'صارفین کو سروس فراہم کرنے والوں کے ساتھ جوڑنا۔',
    sendNotifications: 'بکنگ کی صورتحال کے بارے میں اطلاع کے انتباہات بھیجنا۔',
    customerSupport: 'کسٹمر سپورٹ اور تنازعات کا حل۔',
    platformAnalytics: 'صارف کے تجربے کو بہتر بنانے کے لیے پلیٹ فارم کے تجزیات۔',
    dataSecurity: '3. ڈیٹا کی حفاظت',
    dataSecurityDesc: 'ہم آپ کی ذاتی معلومات کی حفاظت کو برقرار رکھنے کے لیے متعدد حفاظتی اقدامات نافذ کرتے ہیں۔ آپ کی ذاتی معلومات محفوظ نیٹ ورکس کے پیچھے موجود ہوتی ہیں اور صرف محدود تعداد میں ایسے افراد تک قابل رسائی ہوتی ہے جن کے پاس ایسے سسٹمز تک رسائی کے خصوصی حقوق ہوں۔',
    sharingThirdParties: '4. تیسرے فریق کے ساتھ اشتراک',
    sharingThirdPartiesDesc: 'ہم آپ کے رابطے کی تفصیلات سروس فراہم کنندہ کے ساتھ صرف اس وقت شیئر کرتے ہیں جب آپ نے آفر قبول کر لی ہو، جیسا کہ سروس کی درخواست کو پورا کرنے کے لیے درکار ہے۔ ہم آپ کا ذاتی ڈیٹا مارکیٹنگ کے مقاصد کے لیے تیسرے فریق کو فروخت نہیں کرتے۔',
    yourRights: '5. آپ کے حقوق',
    yourRightsDesc: 'آپ کو کسی بھی وقت اپنی اکاؤنٹ کی ترتیبات کے ذریعے یا ہماری سپورٹ ٹیم سے رابطہ کر کے اپنی ذاتی معلومات تک رسائی، درستگی یا حذف کرنے کا حق حاصل ہے۔',

    // Terms & Conditions
    termsTitle: 'شرائط و ضوابط',
    acceptanceTerms: '1. شرائط کی قبولیت',
    acceptanceTermsDesc: 'سروس ٹیپ تک رسائی اور استعمال کر کے، آپ ان شرائط و ضوابط کے پابند ہونے سے اتفاق کرتے ہیں۔ اگر آپ ان شرائط کے کسی بھی حصے سے متفق نہیں ہیں، تو آپ کو ہمارا پلیٹ فارم استعمال نہیں کرنا چاہیے۔',
    userAccounts: '2. صارف اکاؤنٹس',
    userAccountsDesc: 'آپ اپنے اکاؤنٹ کی اسناد کی رازداری برقرار رکھنے کے ذمہ دار ہیں۔ آپ کو رجسٹریشن کے دوران درست اور مکمل معلومات فراہم کرنی چاہئیں۔ سروس ٹیپ غلط معلومات فراہم کرنے والے اکاؤنٹس کو معطل کرنے کا حق محفوظ رکھتا ہے۔',
    bookingPayments: '3. بکنگ اور ادائیگیاں',
    bookingPaymentsDesc: 'صارفین آفر سسٹم میں قبول کی گئی قیمت ادا کرنے پر اتفاق کرتے ہیں۔ ادائیگیاں طے شدہ طریقوں کے ذریعے ہونی چاہئیں۔ سروس ٹیپ ایک مارکیٹ پلیس کے طور پر کام کرتا ہے اور کام کے معیار کے حوالے سے تنازعات کا ذمہ دار نہیں ہے، حالانکہ ہم حل میں مدد فراہم کریں گے۔',
    cancellationsTerms: '4. منسوخی',
    cancellationsTermsDesc: 'اگر طے شدہ وقت کے ایک خاص فریم کے اندر منسوخی کی جاتی ہے تو فیس لاگو ہو سکتی ہے۔ براہ کرم مخصوص منسوخی کی پالیسیوں کے لیے انفرادی سروس فراہم کنندہ کی شرائط ملاحظہ کریں۔',
    proVerification: '5. پیشہ ورانہ تصدیق',
    proVerificationDesc: 'جبکہ سروس ٹیپ بیک گراؤنڈ چیک کرتا ہے، صارفین کو آفرز قبول کرنے سے پہلے اپنے فیصلے کا استعمال کرنے اور ریویوز پڑھنے کی ترغیب دی جاتی ہے۔',
    liabilityLimitation: '6. ذمہ داری کی حد',
    liabilityLimitationDesc: 'سروس ناک ہماری خدمات کے استعمال یا پلیٹ فارم کے ذریعے حاصل کیے گئے آزاد ٹھیکیداروں کے اقدامات کے نتیجے میں ہونے والے کسی بھی بالواسطہ، اتفاقی، یا نتیجہ خیز نقصانات کا ذمہ دار نہیں ہوگا۔',
    voiceDescription: 'آواز کی تفصیل',
    speakIssue: 'بول کر بتائیں',
    stopRecording: 'ریکارڈنگ روکیں',
    recordingStarted: 'ریکارڈنگ شروع ہو گئی...',
    recordingStopped: 'ریکارڈنگ روک دی گئی۔',
    micError: 'مائیکروفون تک رسائی مسترد کر دی گئی۔',
    blockedAccountAlert: 'آپ کا اکاؤنٹ بلاک کر دیا گیا ہے، تفصیلات کے لیے سپورٹ سے رابطہ کریں۔',
    reportProfile: 'پروفائل کی رپورٹ کریں',
    reported: 'رپورٹ کر دیا گیا',
    confirmReport: 'کیا آپ واقعی اس پروفائل کی رپورٹ کرنا چاہتے ہیں؟ 3 رپورٹ ہونے پر یہ اکاؤنٹ خود بخود بلاک ہو جائے گا۔',
    verified: 'تصدیق شدہ',
    unverified: 'غیر تصدیق شدہ',
    identityVerification: 'شناختی تصدیق',
    verifyIdentityDesc: 'اپنے شناختی کارڈ کی واضح تصویر اپ لوڈ کر کے اپنی شناخت کی تصدیق کریں۔ اس سے کمیونٹی میں اعتماد بڑھتا ہے۔',
    uploadCNIC: 'شناختی کارڈ کی تصویر اپ لوڈ کریں',
    verificationPending: 'تصدیق زیر التوا ہے',
    verificationPendingDesc: 'آپ کے شناختی کارڈ کا ہماری ٹیم جائزہ لے رہی ہے۔ اس میں عام طور پر 24 گھنٹے لگتے ہیں۔',
    verificationRejected: 'تصدیق مسترد کر دی گئی',
    verificationRejectedReason: 'وجہ:',
    resubmitID: 'دوبارہ جمع کرائیں',
    submitForVerification: 'تصدیق کے لیے جمع کرائیں',
    verificationSuccess: 'تصدیق کے لیے درخواست جمع کر دی گئی ہے!',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');
  const [direction, setDirection] = useState(language === 'ur' ? 'rtl' : 'ltr');

  useEffect(() => {
    localStorage.setItem('language', language);
    const dir = language === 'ur' ? 'rtl' : 'ltr';
    setDirection(dir);
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    
    // Update fonts for Urdu
    if (language === 'ur') {
      document.body.style.fontFamily = "'Noto Nastaliq Urdu', serif, 'Inter', sans-serif";
    } else {
      document.body.style.fontFamily = "'Inter', system-ui, sans-serif";
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ur' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
