import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    home: 'Home',
    services: 'Services',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    getStarted: 'Get Started',
    myProfile: 'My Profile',
    signOut: 'Sign Out',
    adminPanel: 'Admin Panel',
    bookService: 'Book Service',
    myBookings: 'My Bookings',
    jobRequests: 'Job Requests',
    dashboard: 'Dashboard',
    workers: 'Workers',
    support: 'Support',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    faqs: 'FAQs',
    bookings: 'Bookings',
    jobs: 'Jobs',
    book: 'Book',
    profile: 'Profile',
    ourBlog: 'Our Blog',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    newsletter: 'Newsletter',
    newsletterPlaceholder: 'Your email',
    allRightsReserved: 'All rights reserved.',
    footerDesc: 'Service Knock is your premier hyper-local service booking platform, dedicated to connecting you with highly skilled and trusted professionals in your area. We provide reliable solutions for all your home and business needs, ensuring quality service is just a few clicks away.',
    addressFull: '6th Road, Rawalpindi',
    ac_fridge_repair: 'AC / Fridge Repair',
    steel_fixer: 'Steel Fixer',
    tile_fixer: 'Tile Fixer',
    irfanRashid: 'Irfan Rashid',
    irfanrashid: 'Irfan Rashid',
    'Irfan Rashid': 'Irfan Rashid',
    khurshidAhmedKhan: 'Khurshid Ahmed Khan',
    'Khurshid Ahmed Khan': 'Khurshid Ahmed Khan',
    serviceTapAdmin: 'ServiceTap Admin',
    serviceKnockAdmin: 'Service Knock Admin',
    
    // Hero Section
    heroTitle: 'Professional Home Services at Your Doorstep',
    heroSubtitle: 'Book trusted electricians, plumbers, painters and more in just a few taps. Reliable help for every home need.',
    heroCTA: 'Book a Service Now',
    activePros: 'Active Professionals',
    trustedUsers: 'Trusted Users',
    
    // Services Section
    ourServices: 'Our Services',
    servicesSubtitle: 'We provide a wide range of professional home services to help you with your daily needs.',
    electrician: 'Electrician',
    plumber: 'Plumber',
    ac_fridge_repair: 'AC / Fridge Repair',
    carpenter: 'Carpenter',
    painter: 'Painter',
    mason: 'Mason',
    steel_fixer: 'Steel Fixer',
    labour: 'Labour',
    tile_fixer: 'Tile Fixer',
    ac_repair: 'AC Repair',
    
    // Service Details
    electricianDesc: 'Expert solutions for all your electrical needs — wiring, panel upgrades, lighting, and fault diagnosis.',
    plumberDesc: 'Professional plumbing services for leaks, installations, blockages, and water pressure issues.',
    acFridgeDesc: 'Complete AC and Refrigerator services — installation, deep cleaning, gas refilling, and comprehensive repairs.',
    carpenterDesc: 'Furniture repair, assembly, and custom woodwork from experienced carpenters.',
    painterDesc: 'Fresh coat of paint for your home or office. Quality finish and mess-free service.',
    masonDesc: 'Structural work, bricklaying, and plastering by skilled masons.',
    steelFixerDesc: 'Professional steel reinforcement for slabs, columns, and foundations.',
    labourDesc: 'General manpower for loading, unloading, shifting, and site cleaning.',
    tileFixerDesc: 'Precise tile installation for floors, walls, and bathrooms.',
    
    // Service Features
    faultDiagnosis: 'Fault diagnosis',
    wiringRewiring: 'Wiring & rewiring',
    panelUpgrades: 'Panel upgrades',
    lightFixtures: 'Light fixtures',
    safetyInspections: 'Safety inspections',
    leakRepairs: 'Leak repairs',
    drainCleaning: 'Drain cleaning',
    pipeInstallation: 'Pipe installation',
    waterHeater: 'Water heater',
    tapReplacement: 'Tap replacement',
    deepCleaning: 'Deep cleaning',
    gasRefilling: 'Gas refilling',
    installation: 'Installation',
    fridgeRepair: 'Fridge repair',
    annualService: 'Annual service',
    furnitureRepair: 'Furniture repair',
    doorWindowFix: 'Door/Window fix',
    customWoodwork: 'Custom woodwork',
    lockInstallation: 'Lock installation',
    assembly: 'Assembly',
    interiorPainting: 'Interior painting',
    exteriorPainting: 'Exterior painting',
    wallPutty: 'Wall putty',
    waterproofing: 'Waterproofing',
    stencilWork: 'Stencil work',
    brickwork: 'Brickwork',
    plastering: 'Plastering',
    wallRepair: 'Wall repair',
    concreteWork: 'Concrete work',
    demolition: 'Demolition',
    steelBending: 'Steel bending',
    rebarFixing: 'Rebar fixing',
    slabReinforcement: 'Slab reinforcement',
    meshWork: 'Mesh work',
    welding: 'Welding',
    generalHelp: 'General help',
    loadingUnloading: 'Loading/Unloading',
    debrisRemoval: 'Debris removal',
    siteCleaning: 'Site cleaning',
    packing: 'Packing',
    floorTiling: 'Floor tiling',
    wallTiling: 'Wall tiling',
    grouting: 'Grouting',
    tileReplacement: 'Tile replacement',
    graniteWork: 'Granite work',
    
    // Services Page
    servicesHeader: 'Certified, background-verified professionals ready to solve your home problems.',
    verifiedPros: 'Verified Professionals',
    verifiedProsDesc: 'Every worker is background-checked and ID-verified before onboarding.',
    fastResponse: 'Fast Response',
    fastResponseDesc: 'Average booking-to-assignment time under 30 minutes during business hours.',
    ratedReviewed: 'Rated & Reviewed',
    ratedReviewedDesc: 'Customer reviews after every job keep our quality standards high.',
    bookNow: 'Book Now',
    notSureHeader: 'Not sure what you need?',
    notSureDesc: 'Create a booking and describe your issue — our admin will match you with the right professional.',
    avgTimeLabel: '⏱ Avg Time:',
    ratingLabel: 'Rating',
    
    // About Us Page
    aboutHeroTitle: 'Revolutionizing Local Services',
    aboutHeroSubtitle: 'Service Knock was born with a simple mission: to connect homeowners with the most reliable professionals in their neighborhood through a seamless, digital experience.',
    verifiedWorkers: 'Verified Workers',
    happyCustomers: 'Happy Customers',
    servicesOffered: 'Services Offered',
    citiesCovered: 'Cities Covered',
    ourCoreValues: 'Our Core Values',
    coreValuesSubtitle: 'These principles guide everything we do, from onboarding workers to supporting our customers.',
    trustSafety: 'Trust & Safety',
    trustSafetyDesc: 'Safety is our top priority. Every professional undergoes a multi-step verification process including background checks.',
    qualityService: 'Quality Service',
    qualityServiceDesc: 'We only partner with skilled tradespeople. Our rating system ensures high performance is always rewarded.',
    transparency: 'Transparency',
    transparencyDesc: 'No hidden fees. Upfront estimates and a clear bidding system mean you always know what you are paying for.',
    builtModernHome: 'Built for the Modern Home',
    modernHomeDesc: 'We understand that finding a reliable electrician or plumber can be stressful. That\'s why we\'ve built a platform that removes the friction. With real-time tracking, transparent pricing, and verified reviews, we\'re bringing local services into the 21st century.',
    support247: '24/7 Customer Support',
    securePayments: 'Secure Online Payments',
    qualityGuarantee: 'Quality Guarantee on Jobs',
    
    // Contact Us Page
    contactHeroSubtitle: 'Have questions? We\'re here to help. Reach out to us through any of these channels.',
    callUs: 'Call Us',
    monFri: 'Mon-Fri: 9am - 6pm',
    emailUs: 'Email Us',
    replyWithin24: 'We reply within 24 hours',
    visitUs: 'Visit Us',
    headquarters: 'Headquarters',
    subject: 'Subject',
    howCanWeHelp: 'How can we help?',
    message: 'Message',
    yourMessageHere: 'Your message here...',
    sendMessage: 'Send Message',
    
    // FAQ Page
    faqSubtitle: 'Everything you need to know about Service Knock — Pakistan\'s trusted hyper-local service platform.',
    stillHaveQuestions: 'Still have questions?',
    supportDesc: 'We\'re here to help. Reach out to our friendly support team for any assistance.',
    contactSupport: 'Contact Support',
    faqQ1: 'How do I book a service?',
    faqA1: 'To book a service, register as a customer, click on \'Book Now\', select your service type, and describe your issue. You can even upload photos or a voice note. Our system will notify nearby verified professionals who will then send you price offers.',
    faqQ2: 'How are workers verified?',
    faqA2: 'Every worker undergoes a mandatory manual verification. They must upload a clear photo of their CNIC (National ID) and professional certifications. Our admin team manually reviews each document before they are allowed to bid on jobs.',
    faqQ3: 'When do I pay for the service?',
    faqA3: 'Payment is made directly to the professional after the job is completed to your satisfaction. You can discuss the payment method (Cash, Bank Transfer, etc.) with the worker during the booking.',
    faqQ4: 'What if I\'m not satisfied with the work?',
    faqA4: 'Service Knock provides a rating and review system to maintain quality. If a major issue occurs, please report the worker profile or contact our support team. We take quality very seriously and block workers who receive multiple complaints.',
    faqQ5: 'Can I cancel a booking?',
    faqA5: 'Yes, you can cancel a booking from your dashboard before it is accepted. If a worker has already been assigned, we request you to notify them as soon as possible as a courtesy.',
    faqQ6: 'How does the Bidding/Offer system work?',
    faqA6: 'When you post a job, workers see your request and send a "Price Offer". You can compare multiple offers based on price, worker ratings, and experience, then choose the one that suits you best.',
    faqQ7: 'Is my personal data safe?',
    faqA7: 'Yes, we use industry-standard encryption. Your phone number and address are only shared with the specific professional you choose to hire for a job.',
    faqQ8: 'Why do I need to provide my CNIC?',
    faqA8: 'For workers, CNIC is mandatory to ensure the safety of our customers. Your ID card image will not be stored permanently — it is deleted after your identity is verified and your profile is approved. We do not store your ID card after verification. For customers, it builds trust and helps prevent fraudulent bookings.',
    
    // Dashboards
    myBookingsTitle: 'My Bookings',
    workerDashboard: 'Worker Dashboard',
    totalSpending: 'Total Spending',
    totalEarnings: 'Total Earnings',
    noBookings: 'No bookings found',
    noJobs: 'No jobs found',
    available: 'Available',
    offersSent: 'Offers Sent',
    active: 'Active',
    completed: 'Completed',
    all: 'All',
    pending: 'Pending',
    assigned: 'Assigned',
    accepted: 'Accepted',
    cancelled: 'Cancelled',
    dashboardSubtitle: 'Manage your service requests and active jobs.',
    activeJobs: 'Active Jobs',
    activeJobsDesc: 'Jobs you have accepted — mark them complete when done.',
    noActiveJobs: 'No active jobs',
    noActiveJobsDesc: 'Accept a job from Job Requests to see it here.',
    
    // Booking Card
    jobPrice: 'Job Price',
    worker: 'Worker',
    customer: 'Customer',
    reviews: 'reviews',
    viewImage: 'View Image',
    status: 'Status',
    date: 'Date',
    details: 'Details',
    
    // Auth
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    name: 'Full Name',
    fullName: 'Full Name',
    phone: 'Phone Number',
    registerAs: 'Register As',
    alreadyHaveAccount: 'Already have an account? Sign In',
    dontHaveAccount: "Don't have an account?",
    forgotPassword: 'Forgot Password?',
    
    // Common
    loading: 'Loading...',
    saving: 'Saving...',
    submitting: 'Submitting...',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    back: 'Back',
    submit: 'Submit',
    availability: 'Availability',
    availableDescription: 'You are currently available for new jobs.',
    unavailableDescription: 'You are currently unavailable.',
    updating: 'Updating...',
    yearsExperience: 'Years of Experience',
    bio: 'Bio',
    bioPlaceholder: 'Tell customers about yourself and your experience...',
    loadingError: 'Failed to load profile.',
    actionFailed: 'Failed to update availability.',
    profileUpdatedToast: 'Profile updated!',
    updateError: 'Failed to update profile.',
    verified: 'Verified',
    unverified: 'Pending Verification',
    viewMore: 'View More',
    search: 'Search',
    address: 'Address',
    description: 'Description',
    title: 'Title',
    
    // My Bookings Dashboard
    viewOffers: 'View Offers',
    edit: 'Edit',
    delete: 'Delete',
    leaveReview: 'Leave Review',
    reviewSubmitted: 'Review Submitted',
    workerOffers: 'Worker Offers',
    noOffersYet: 'No offers received yet. Please wait for workers to respond.',
    acceptOffer: 'Accept Offer',
    accepting: 'Accepting...',
    editJobPost: 'Edit Job Post',
    jobTitle: 'Job Title',
    leaveAReview: 'Leave a Review',
    rating: 'Rating',
    commentOptional: 'Comment (optional)',
    tellUsAboutExperience: 'Tell us about your experience...',
    noBookingsYet: 'You haven\'t made any bookings yet.',
    noFilteredBookings: 'No {status} bookings found.',
    offerAcceptedToast: 'Offer accepted! The worker has been notified.',
    jobDeletedToast: 'Job post deleted.',
    jobUpdatedToast: 'Job updated successfully!',
    reviewSubmittedToast: 'Review submitted! Thank you.',
    
    // Job Requests Dashboard (Worker)
    orCounterOffer: 'Or Counter Offer',
    yourPrice: 'Your Price (Rs.)',
    customPrice: 'Custom price',
    sendCustomOffer: 'Send Custom Offer',
    sending: 'Sending...',
    yourBid: 'Your Bid:',
    waitingForCustomer: 'Waiting for Customer...',
    markCompleted: 'Mark Completed',
    completing: 'Completing...',
    rateCustomer: 'Rate Customer',
    ratedCustomer: 'Rated Customer',
    howWasExperienceWithCustomer: 'How was your experience with this customer?',
    noJobsFound: 'No jobs found',
    noPendingJobsDesc: 'There are no pending jobs for your service type right now.',
    noOffersSentDesc: 'You haven\'t sent any offers yet.',
    noActiveJobsDesc: 'You don\'t have any active jobs.',
    noCompletedJobsDesc: 'No completed jobs yet.',
    offerSentToast: 'Offer sent successfully!',
    jobAcceptedToast: 'Job accepted and added to your active list!',
    jobCompletedToast: 'Job marked as completed!',
    customerReviewToast: 'Review submitted for customer!',
    
    // Book Service Page
    bookServiceSubtitle: 'Fill in the details and we\'ll match you with a verified professional.',
    jobTitlePlaceholder: 'e.g. Fix living room light',
    describeIssue: 'Describe Your Issue',
    issuePlaceholder: 'e.g. My kitchen light keeps flickering...',
    serviceAddress: 'Service Address',
    addressPlaceholder: 'Type your address in Pakistan...',
    jobPhotosOptional: 'Job Photos (Optional)',
    uploadPhoto: 'Upload Photo',
    priceEstimateLabel: 'Price Estimate (Rs.)',
    preferredDateTime: 'Preferred Date/Time',
    submitBooking: 'Submit Booking',
    selectServiceType: 'Please select a service type',
    bookingSubmittedToast: 'Booking submitted! We\'ll assign a worker shortly.',
    suggestionsTitle: 'Suggestions (Pakistan Only)',
    fileTooLarge: 'File too large. Max 5MB allowed.',
    selectService: 'Select Service',
    
    // Profile Page
    editProfile: 'Edit Profile',
    joined: 'Joined',
    userReviews: 'User Reviews',
    noReviewsYet: 'No reviews received yet.',
    untitledService: 'Untitled Service',
    noCommentProvided: 'No comment provided',
    recentJobs: 'Recent Jobs',
    noJobHistory: 'No job history.',
    choosePhoto: 'Choose Photo',
    profileUpdatedToast: 'Profile updated!',
    profileNotFound: 'Profile not found.',
    profilePicture: 'Profile Picture',
    fileTypeLimit: 'PNG, JPG or GIF up to 5MB',
    
    // Home Page
    fastBooking: 'Fast booking in under 60 seconds',
    heroTitleMain: 'Book Trusted Home',
    heroTitleSub: 'Service Professionals',
    verifiedWorkersShort: 'Verified Workers',
    ratedReviewed: 'Rated & Reviewed',
    fastResponse: 'Fast Response',
    howItWorks: 'How It Works',
    threeSteps: '3 simple steps to get your issue resolved',
    whatCustomersSay: 'What Customers Say',
    trustedHomeowners: 'Trusted by thousands of homeowners',
    readyToStart: 'Ready to get started?',
    ctaBannerDesc: 'Join thousands of happy customers. Book your first service in under 60 seconds.',
    pickAService: 'Pick a Service',
    pickAServiceDesc: 'Choose from Electrician, Plumber, AC Technician, or Carpenter.',
    submitRequest: 'Submit Request',
    submitRequestDesc: 'Describe your issue and add your address in seconds.',
    jobDone: 'Job Done',
    jobDoneDesc: 'Worker arrives, completes the job, you rate them.',
    happyCustomersLabel: 'Happy Customers',
    jobsCompletedLabel: 'Jobs Completed',
    avgRatingLabel: 'Average Rating',
    satisfactionRateLabel: 'Satisfaction Rate',
    saraKhan: 'Sara Khan',
    homeowner: 'Homeowner',
    saraTestimonial: 'The electrician from Service Knock arrived in under 2 hours. He was super professional and fixed my wiring issues perfectly!',
    aliHaider: 'Ali Haider',
    businessOwner: 'Business Owner',
    aliTestimonial: 'Used Service Knock for our office AC repair. The service was fast, affordable, and the worker was verified. Highly recommend.',
    asimIqbal: 'Asim Iqbal',
    apartmentTenant: 'Apartment Tenant',
    asimTestimonial: 'Booked a plumber from Service Knock at 9pm and had it sorted by morning. Amazing speed and quality service for our family.',
    bilalSiddiqui: 'Bilal Siddiqui',
    interiorDesigner: 'Interior Designer',
    bilalTestimonial: 'Found a great carpenter through Service Knock to fix my kitchen cabinets. Exceptional quality and very reasonable pricing.',
    maryamJaved: 'Maryam Javed',
    doctor: 'Doctor',
    maryamTestimonial: 'Service Knock is my go-to for any home repairs. Their workers are punctual, skilled, and the booking process is extremely smooth.',
    zainabRaza: 'Zainab Raza',
    teacher: 'Teacher',
    zainabTestimonial: 'Extremely satisfied with the plumber from Service Knock. He diagnosed the leak quickly and fixed it without any mess or hassle.',
    
    // Financials
    spendingTotal: 'Total Spending',
    earningsTotal: 'Total Earnings',
    urduNameLabel: 'Name in Urdu',
    
    // Privacy Policy
    privacyTitle: 'Privacy Policy',
    lastUpdated: 'Last Updated: May 2026',
    infoCollect: '1. Information We Collect',
    infoCollectDesc: 'Service Knock collects personal information to provide a safe and reliable marketplace. This includes:',
    accountInfo: 'Personal Details: Name, email, and 11-digit verified phone number.',
    bookingData: 'Service Data: Job descriptions, addresses, and photos of the issue.',
    paymentData: 'Identity Documents: For workers, we collect CNIC (National ID) images for mandatory verification. Your ID card image is permanently deleted after verification and profile approval — we do not store your ID card.',
    howWeUse: '2. How We Use Your Information',
    howWeUseDesc: 'Your information is used solely to facilitate the connection between customers and service providers. We use it to:',
    connectCustomers: 'Enable workers to see job requests in their area.',
    sendNotifications: 'Provide real-time updates via SMS or platform notifications.',
    customerSupport: 'Verify the identity of professionals to ensure customer safety.',
    platformAnalytics: 'Resolve disputes and provide customer support.',
    dataSecurity: '3. Data Security & CNIC Protection',
    dataSecurityDesc: 'We take identification data very seriously. CNIC images are used only for manual verification and are permanently deleted after your profile is approved. We do not store your ID card.',
    sharingThirdParties: '4. Information Sharing',
    sharingThirdPartiesDesc: 'Your contact information (Phone/Address) is only shared with a professional AFTER you accept their offer. We never sell your data to third-party marketing agencies.',
    yourRights: '5. Your Rights',
    yourRightsDesc: 'You can update your profile, request data deletion, or withdraw your verification documents at any time by contacting support, though this may limit your access to the platform.',
    
    // Terms & Conditions
    termsTitle: 'Terms & Conditions',
    acceptanceTerms: '1. Acceptance of Terms',
    acceptanceTermsDesc: 'By registering on Service Knock, you agree to comply with our community standards and service rules. This platform is a marketplace for local home services in Pakistan.',
    userAccounts: '2. Account Responsibility',
    userAccountsDesc: 'Users must provide real names and accurate information. Workers must complete mandatory CNIC verification before bidding. Misuse of the platform or fraudulent profiles will result in an immediate permanent block.',
    bookingPayments: '3. Bidding & Pricing',
    bookingPaymentsDesc: 'Workers provide "Price Offers" based on customer descriptions. Once an offer is accepted, it constitutes a formal agreement. Customers are responsible for paying the professional directly upon completion.',
    cancellationsTerms: '4. Cancellations',
    cancellationsTermsDesc: 'Repeated cancellations by either customers or workers may lead to account restrictions. We value the time of our service professionals.',
    proVerification: '5. Professional Conduct',
    proVerificationDesc: 'Service Knock is a platform for connection. While we verify IDs, we do not employ the workers. Your ID card image is deleted after verification and profile approval — we do not permanently store it. Customers should exercise normal caution and verify the work before payment.',
    liabilityLimitation: '6. Limitation of Liability',
    liabilityLimitationDesc: 'Service Knock is not responsible for any damages, losses, or poor workmanship by independent contractors. We act as a facilitator and provide a review system for accountability.',
    voiceDescription: 'Voice Description',
    speakIssue: 'Speak Issue',
    stopRecording: 'Stop Recording',
    recordingStarted: 'Recording started...',
    recordingStopped: 'Recording stopped.',
    micError: 'Microphone access denied.',
    blockedAccountAlert: 'Your account is blocked please contact support for details.',
    reportProfile: 'Report Profile',
    reported: 'Reported',
    confirmReport: 'Are you sure you want to report this profile? Multiple reports will lead to automatic account block.',
    verified: 'Verified',
    unverified: 'Unverified',
    identityVerification: 'Identity Verification',
    verifyIdentityDesc: 'Verify your identity by uploading a clear photo of your CNIC. This builds trust in the community.',
    uploadCNIC: 'Upload CNIC Photo',
    verificationPending: 'Verification Pending',
    verificationPendingDesc: 'Your ID is being reviewed by our team. This usually takes 24 hours.',
    verificationRejected: 'Verification Rejected',
    verificationRejectedReason: 'Reason:',
    resubmitID: 'Resubmit ID',
    submitForVerification: 'Submit for Verification',
    verificationSuccess: 'Verification submitted successfully!',
    cropProfilePicture: 'Crop Profile Picture',
    reset: 'Reset',
    apply: 'Apply',
    supportChat: 'Support Chat',
    onlineBotAgents: 'Online | Auto Bot & Agents',
    howCanWeHelpYou: 'How can we help you today?',
    typeYourMessage: 'Type your message...',
    supportChats: 'Support Chats',
    searchUsers: 'Search users...',
    selectConversation: 'Select a conversation to start chatting',
    respondToQueries: 'Respond to user queries and view chat history.',
    typeAResponse: 'Type a response...',
    restartLiveServer: 'Restart Live Server',
    restartConfirm: 'Are you sure you want to pull latest changes and restart the live server?',
    restarting: 'Restarting...',
  },
  ur: {
    // Navbar
    home: 'ہوم',
    services: 'خدمات',
    about: 'ہمارے بارے میں',
    contact: 'رابطہ کریں',
    login: 'لاگ ان',
    getStarted: 'شروع کریں',
    myProfile: 'میری پروفائل',
    signOut: 'سائن آؤٹ',
    adminPanel: 'ایڈمن پینل',
    bookService: 'سروس بک کریں',
    myBookings: 'میری بکنگز',
    jobRequests: 'کام کی درخواستیں',
    dashboard: 'ڈیش بورڈ',
    workers: 'ورکرز',
    support: 'سپورٹ',
    aboutUs: 'ہمارے بارے میں',
    contactUs: 'رابطہ کریں',
    faqs: 'عام سوالات',
    bookings: 'بکنگز',
    jobs: 'کام',
    book: 'بک کریں',
    profile: 'پروفائل',
    ourBlog: 'ہمارا بلاگ',
    privacyPolicy: 'پرائیویسی پالیسی',
    termsConditions: 'شرائط و ضوابط',
    newsletter: 'نیوز لیٹر',
    newsletterPlaceholder: 'آپ کا ای میل',
    allRightsReserved: 'تمام حقوق محفوظ ہیں۔',
    footerDesc: 'سروس ناک آپ کا بہترین مقامی سروس بکنگ پلیٹ فارم ہے، جو آپ کو آپ کے علاقے میں انتہائی ماہر اور قابل اعتماد پیشہ ور افراد سے جوڑنے کے لیے وقف ہے۔ ہم آپ کے گھر اور کاروبار کی تمام ضروریات کے لیے قابل اعتماد حل فراہم کرتے ہیں، اس بات کو یقینی بناتے ہوئے کہ معیاری سروس صرف چند کلکس کے فاصلے پر ہو۔',
    addressFull: 'سکسٹھ روڈ، راولپنڈی',

    // Hero Section
    heroTitle: 'پیشہ ورانہ گھریلو خدمات آپ کی دہلیز پر',
    heroSubtitle: 'صرف چند کلکس میں بھروسہ مند الیکٹریشن، پلمبر، پینٹر اور بہت کچھ بک کریں۔ ہر گھر کی ضرورت کے لیے قابل اعتماد مدد۔',
    heroCTA: 'ابھی سروس بک کریں',
    activePros: 'فعال پیشہ ور افراد',
    trustedUsers: 'بھروسہ مند صارفین',
    
    // Services Section
    ourServices: 'ہماری خدمات',
    servicesSubtitle: 'ہم آپ کی روزمرہ کی ضروریات میں مدد کے لیے پیشہ ورانہ گھریلو خدمات کی ایک وسیع رینج فراہم کرتے ہیں۔',
    electrician: 'الیکٹریشن',
    plumber: 'پلمبر',
    ac_fridge_repair: 'اے سی / فریج کی مرمت',
    carpenter: 'بڑھئی',
    painter: 'پینٹر',
    mason: 'راج مستری',
    steel_fixer: 'سٹیل فکسر',
    labour: 'مزدور',
    tile_fixer: 'ٹائل فکسر',
    ac_repair: 'اے سی کی مرمت',
    irfanRashid: 'عرفان رشید',
    irfanrashid: 'عرفان رشید',
    'Irfan Rashid': 'عرفان رشید',
    khurshidAhmedKhan: 'خورشید احمد خان',
    'Khurshid Ahmed Khan': 'خورشید احمد خان',
    serviceTapAdmin: 'سروس ٹیپ ایڈمن',
    serviceKnockAdmin: 'سروس ناک ایڈمن',
    faizanTraders: 'فیضان ٹریڈرز',
    'Faizan Traders': 'فیضان ٹریڈرز',
    faizan: 'فیضان',
    traders: 'ٹریڈرز',
    abdulRaheemSufi: 'عبدالرحیم صوفی',
    'Abdul Raheem Sufi': 'عبدالرحیم صوفی',
    abdul: 'عبدال',
    raheem: 'رحیم',
    sufi: 'صوفی',
    irfan: 'عرفان',
    rashid: 'رشید',
    ali: 'علی',
    haider: 'حیدر',
    asim: 'عاصم',
    iqbal: 'اقبال',
    bilal: 'بلال',
    siddiqui: 'صدیقی',
    maryam: 'مریم',
    javed: 'جاوید',
    zainab: 'زینب',
    raza: 'رضا',
    sara: 'سارہ',
    khan: 'خان',

    // Service Details
    electricianDesc: 'آپ کی تمام برقی ضروریات کے لیے ماہرانہ حل — وائرنگ، پینل اپ گریڈ، لائٹنگ، اور خرابی کی تشخیص۔',
    plumberDesc: 'لیک، انسٹالیشن، بلاکج، اور پانی کے پریشر کے مسائل کے لیے پیشہ ورانہ پلمبنگ سروسز۔',
    acFridgeDesc: 'مکمل اے سی اور ریفریجریٹر سروسز — انسٹالیشن، گہری صفائی، گیس ری فلنگ، اور جامع مرمت۔',
    carpenterDesc: 'تجربہ کار بڑھئیوں سے فرنیچر کی مرمت، اسمبلی، اور کسٹم لکڑی کا کام۔',
    painterDesc: 'آپ کے گھر یا دفتر کے لیے پینٹ کا نیا کوٹ۔ معیاری فنش اور گندگی سے پاک سروس۔',
    masonDesc: 'ماہر راج مستریوں کے ذریعے تعمیراتی کام، اینٹوں کی چنائی، اور پلستر۔',
    steelFixerDesc: 'سلیب، کالموں اور بنیادوں کے لیے پیشہ ورانہ سٹیل کی مضبوطی۔',
    labourDesc: 'لوڈنگ، ان لوڈنگ، شفٹنگ، اور سائٹ کی صفائی کے لیے عام افرادی قوت۔',
    tileFixerDesc: 'فرش، دیواروں اور باتھ رومز کے لیے درست ٹائل انسٹالیشن۔',
    
    // Service Features
    faultDiagnosis: 'خرابی کی تشخیص',
    wiringRewiring: 'وائرنگ اور ری وائرنگ',
    panelUpgrades: 'پینل اپ گریڈ',
    lightFixtures: 'لائٹ فکسچر',
    safetyInspections: 'حفاظتی معائنہ',
    leakRepairs: 'لیک کی مرمت',
    drainCleaning: 'ڈرین کی صفائی',
    pipeInstallation: 'پائپ کی تنصیب',
    waterHeater: 'واٹر ہیٹر',
    tapReplacement: 'نل کی تبدیلی',
    deepCleaning: 'گہری صفائی',
    gasRefilling: 'گیس ری فلنگ',
    installation: 'انسٹالیشن',
    fridgeRepair: 'فریج کی مرمت',
    annualService: 'سالانہ سروس',
    furnitureRepair: 'فرنیچر کی مرمت',
    doorWindowFix: 'دروازہ/کھڑکی کی مرمت',
    customWoodwork: 'کسٹم لکڑی کا کام',
    lockInstallation: 'لاک کی تنصیب',
    assembly: 'اسمبلی',
    interiorPainting: 'اندرونی پینٹنگ',
    exteriorPainting: 'بیرونی پینٹنگ',
    wallPutty: 'وال پٹی',
    waterproofing: 'واٹر پروفنگ',
    stencilWork: 'سٹینسل ورک',
    brickwork: 'اینٹوں کا کام',
    plastering: 'پلستر',
    wallRepair: 'دیوار کی مرمت',
    concreteWork: 'کنکریٹ کا کام',
    demolition: 'انہدام',
    steelBending: 'سٹیل موڑنا',
    rebarFixing: 'ریبار فکسنگ',
    slabReinforcement: 'سلیب کی مضبوطی',
    meshWork: 'میش ورک',
    welding: 'ویلڈنگ',
    generalHelp: 'عام مدد',
    loadingUnloading: 'لوڈنگ/ان لوڈنگ',
    debrisRemoval: 'ملبہ ہٹانا',
    siteCleaning: 'سائٹ کی صفائی',
    packing: 'پیکنگ',
    floorTiling: 'فرش کی ٹائلیں',
    wallTiling: 'دیوار کی ٹائلیں',
    grouting: 'گراؤٹنگ',
    tileReplacement: 'ٹائل کی تبدیلی',
    graniteWork: 'گرینائٹ کا کام',

    // Services Page
    servicesHeader: 'تصدیق شدہ، بیک گراؤنڈ سے تصدیق شدہ پیشہ ور افراد آپ کے گھر کے مسائل حل کرنے کے لیے تیار ہیں۔',
    verifiedPros: 'تصدیق شدہ پیشہ ور افراد',
    verifiedProsDesc: 'آن بورڈنگ سے پہلے ہر ورکر کا بیک گراؤنڈ اور شناختی کارڈ چیک کیا جاتا ہے۔',
    fastResponse: 'تیز ردعمل',
    fastResponseDesc: 'کاروباری اوقات کے دوران اوسط بکنگ سے اسائنمنٹ کا وقت 30 منٹ سے کم ہے۔',
    ratedReviewed: 'درجہ بندی اور جائزہ',
    ratedReviewedDesc: 'ہر کام کے بعد کسٹمر کے جائزے ہمارے معیار کو برقرار رکھتے ہیں۔',
    bookNow: 'ابھی بک کریں',
    notSureHeader: 'پتہ نہیں آپ کو کیا چاہیے؟',
    notSureDesc: 'بکنگ بنائیں اور اپنے مسئلے کی وضاحت کریں — ہمارا ایڈمن آپ کو صحیح پیشہ ور سے ملا دے گا۔',
    avgTimeLabel: '⏱ اوسط وقت:',
    ratingLabel: 'درجہ بندی',

    // About Us Page
    aboutHeroTitle: 'مقامی خدمات میں انقلاب لانا',
    aboutHeroSubtitle: 'سروس ناک ایک سادہ مشن کے ساتھ پیدا ہوا تھا: گھر کے مالکان کو ایک ہموار، ڈیجیٹل تجربے کے ذریعے ان کے پڑوس کے سب سے زیادہ قابل اعتماد پیشہ ور افراد کے ساتھ جوڑنا۔',
    verifiedWorkers: 'تصدیق شدہ ورکرز',
    happyCustomers: 'خوش حال صارفین',
    servicesOffered: 'پیش کردہ خدمات',
    citiesCovered: 'شامل شہر',
    ourCoreValues: 'ہماری بنیادی اقدار',
    coreValuesSubtitle: 'یہ اصول ہمارے ہر کام میں ہماری رہنمائی کرتے ہیں، ورکرز کی بھرتی سے لے کر اپنے صارفین کی مدد تک۔',
    trustSafety: 'بھروسہ اور حفاظت',
    trustSafetyDesc: 'حفاظت ہماری اولین ترجیح ہے۔ ہر پیشہ ور بیک گراؤنڈ چیک سمیت متعدد مراحل کے تصدیقی عمل سے گزرتا ہے۔',
    qualityService: 'معیاری سروس',
    qualityServiceDesc: 'ہم صرف ماہر کاریگروں کے ساتھ شراکت داری کرتے ہیں۔ ہمارا ریٹنگ سسٹم اس بات کو یقینی بناتا ہے کہ اچھی کارکردگی کا ہمیشہ صلہ ملے۔',
    transparency: 'شفافیت',
    transparencyDesc: 'کوئی پوشیدہ فیس نہیں۔ پہلے سے تخمینہ اور واضح بولی لگانے کا نظام مطلب ہے کہ آپ ہمیشہ جانتے ہیں کہ آپ کس چیز کی ادائیگی کر رہے ہیں۔',
    builtModernHome: 'جدید گھر کے لیے تیار',
    modernHomeDesc: 'ہم سمجھتے ہیں کہ قابل اعتماد الیکٹریشن یا پلمبر تلاش کرنا مشکل ہو سکتا ہے۔ اسی لیے ہم نے ایک ایسا پلیٹ فارم بنایا ہے جو اس مشکل کو ختم کرتا ہے۔ ریئل ٹائم ٹریکنگ، شفاف قیمتوں اور تصدیق شدہ جائزوں کے ساتھ، ہم مقامی خدمات کو 21 ویں صدی میں لے جا رہے ہیں۔',
    support247: '24/7 کسٹمر سپورٹ',
    securePayments: 'محفوظ آن لائن ادائیگیاں',
    qualityGuarantee: 'کام پر معیار کی ضمانت',

    // Contact Us Page
    contactHeroSubtitle: 'سوالات ہیں؟ ہم مدد کے لیے حاضر ہیں۔ ان میں سے کسی بھی چینل کے ذریعے ہم سے رابطہ کریں۔',
    callUs: 'ہمیں کال کریں',
    monFri: 'پیر تا جمعہ: صبح 9 بجے سے شام 6 بجے تک',
    emailUs: 'ہمیں ای میل کریں',
    replyWithin24: 'ہم 24 گھنٹوں کے اندر جواب دیتے ہیں',
    visitUs: 'ہمارے ہاں تشریف لائیں',
    headquarters: 'ہیڈ کوارٹر',
    subject: 'موضوع',
    howCanWeHelp: 'ہم آپ کی کیا مدد کر سکتے ہیں؟',
    message: 'پیغام',
    yourMessageHere: 'آپ کا پیغام یہاں...',
    sendMessage: 'پیغام بھیجیں',

    // FAQ Page
    faqSubtitle: 'سروس ناک کے بارے میں ہر وہ چیز جو آپ کو جاننے کی ضرورت ہے - پاکستان کا قابل اعتماد لوکل سروس پلیٹ فارم۔',
    stillHaveQuestions: 'اب بھی سوالات ہیں؟',
    supportDesc: 'ہم مدد کے لیے حاضر ہیں۔ کسی بھی قسم کی مدد کے لیے ہماری دوستانہ سپورٹ ٹیم سے رابطہ کریں۔',
    contactSupport: 'سپورٹ سے رابطہ کریں',
    faqQ1: 'میں سروس کیسے بک کروں؟',
    faqA1: 'سروس بک کرنے کے لیے، بطور گاہک رجسٹر ہوں، \'ابھی بک کریں\' پر کلک کریں، اپنی سروس کی قسم منتخب کریں، اور اپنے مسئلے کی وضاحت کریں۔ آپ تصاویر یا وائس نوٹ بھی اپ لوڈ کر سکتے ہیں۔ ہمارا سسٹم قریبی تصدیق شدہ ورکرز کو مطلع کرے گا جو پھر آپ کو قیمت کی پیشکش بھیجیں گے۔',
    faqQ2: 'ورکرز کی تصدیق کیسے کی جاتی ہے؟',
    faqA2: 'ہر ورکر لازمی دستی تصدیق سے گزرتا ہے۔ انہیں اپنے شناختی کارڈ (CNIC) اور پیشہ ورانہ سرٹیفکیٹ کی واضح تصویر اپ لوڈ کرنی ہوتی ہے۔ ہماری ایڈمن ٹیم ہر دستاویز کا خود جائزہ لیتی ہے اس سے پہلے کہ انہیں بولی لگانے کی اجازت دی جائے۔',
    faqQ3: 'میں سروس کے لیے کب ادائیگی کروں؟',
    faqA3: 'ادائیگی کام مکمل ہونے اور آپ کے مطمئن ہونے کے بعد براہ راست ورکر کو کی جاتی ہے۔ آپ بکنگ کے دوران ورکر کے ساتھ ادائیگی کے طریقے (کیش، بینک ٹرانسفر وغیرہ) پر بات کر سکتے ہیں۔',
    faqQ4: 'اگر میں کام سے مطمئن نہ ہوں تو کیا ہوگا؟',
    faqA4: 'سروس ناک معیار برقرار رکھنے کے لیے ریٹنگ اور ریویو سسٹم فراہم کرتا ہے۔ اگر کوئی بڑا مسئلہ ہو تو براہ کرم ورکر کی پروفائل رپورٹ کریں یا ہماری سپورٹ ٹیم سے رابطہ کریں۔ ہم معیار کو بہت سنجیدگی سے لیتے ہیں اور ان ورکرز کو بلاک کر دیتے ہیں جن کی بار بار شکایات آتی ہیں۔',
    faqQ5: 'کیا میں بکنگ منسوخ کر سکتا ہوں؟',
    faqA5: 'جی ہاں، آپ آفر قبول ہونے سے پہلے اپنے ڈیش بورڈ سے بکنگ منسوخ کر سکتے ہیں۔ اگر ورکر پہلے ہی مقرر ہو چکا ہے، تو ہم آپ سے درخواست کرتے ہیں کہ انہیں جلد از جلد مطلع کریں تاکہ ان کا وقت ضائع نہ ہو۔',
    faqQ6: 'بولی لگانے یا آفر کا نظام کیسے کام کرتا ہے؟',
    faqA6: 'جب آپ کام پوسٹ کرتے ہیں، ورکرز آپ کی درخواست دیکھتے ہیں اور "قیمت کی آفر" بھیجتے ہیں۔ آپ قیمت، ورکر کی ریٹنگ اور تجربے کی بنیاد پر متعدد آفرز کا موازنہ کر سکتے ہیں، پھر وہ منتخب کریں جو آپ کے لیے موزوں ہو۔',
    faqQ7: 'کیا میرا ذاتی ڈیٹا محفوظ ہے؟',
    faqA7: 'جی ہاں، ہم جدید ترین انکرپشن کا استعمال کرتے ہیں۔ آپ کا فون نمبر اور پتہ صرف اس ورکر کے ساتھ شیئر کیا جاتا ہے جسے آپ کام کے لیے منتخب کرتے ہیں۔',
    faqQ8: 'مجھے اپنا شناختی کارڈ کیوں فراہم کرنا ہوگا؟',
    faqA8: 'ورکرز کے لیے، ہمارے صارفین کی حفاظت کو یقینی بنانے کے لیے شناختی کارڈ لازمی ہے۔ آپ کی شناختی کارڈ کی تصویر مستقل طور پر محفوظ نہیں رکھی جائے گی — تصدیق اور پروفائل کی منظوری کے بعد حذف کر دی جاتی ہے۔ ہم آپ کا شناختی کارڈ نہیں رکھتے۔ صارفین کے لیے، یہ اعتماد پیدا کرتا ہے اور جعلی بکنگ کو روکنے میں مدد دیتا ہے۔',

    // Dashboards
    myBookingsTitle: 'میری بکنگز',
    workerDashboard: 'ورکر ڈیش بورڈ',
    totalSpending: 'کل خرچ',
    totalEarnings: 'کل آمدنی',
    noBookings: 'کوئی بکنگ نہیں ملی',
    noJobs: 'کوئی کام نہیں ملا',
    available: 'دستیاب',
    offersSent: 'بھیجی گئی پیشکشیں',
    active: 'فعال',
    completed: 'مکمل',
    all: 'تمام',
    pending: 'زیر التواء',
    assigned: 'نامزد',
    accepted: 'قبول شدہ',
    cancelled: 'منسوخ',
    dashboardSubtitle: 'اپنی سروس کی درخواستوں اور فعال کاموں کا انتظام کریں۔',
    activeJobs: 'فعال کام',
    activeJobsDesc: 'وہ کام جو آپ نے قبول کیے ہیں — مکمل ہونے پر انہیں مکمل نشان زد کریں۔',
    noActiveJobs: 'کوئی فعال کام نہیں ہے',
    noActiveJobsDesc: 'یہاں دیکھنے کے لیے جاب ریکویسٹ سے کوئی کام قبول کریں۔',
    
    // Booking Card
    jobPrice: 'کام کی قیمت',
    worker: 'ورکر',
    customer: 'گاہک',
    reviews: 'تبصرے',
    viewImage: 'تصویر دیکھیں',
    status: 'صورتحال',
    date: 'تاریخ',
    details: 'تفصیلات',
    
    // Auth
    welcomeBack: 'خوش آمدید',
    createAccount: 'اکاؤنٹ بنائیں',
    email: 'ای میل ایڈریس',
    password: 'پاس ورڈ',
    name: 'پورا نام',
    fullName: 'پورا نام',
    phone: 'فون نمبر',
    registerAs: 'بطور رجسٹر ہوں',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    forgotPassword: 'پاس ورڈ بھول گئے؟',
    
    // Common
    loading: 'لوڈ ہو رہا ہے...',
    saving: 'محفوظ ہو رہا ہے...',
    submitting: 'جمع ہو رہا ہے...',
    cancel: 'منسوخ کریں',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    back: 'واپس',
    submit: 'جمع کرائیں',
    availability: 'دستیابی',
    availableDescription: 'آپ فی حال نئے کاموں کے لیے دستیاب ہیں۔',
    unavailableDescription: 'آپ فی حال دستیاب نہیں ہیں۔',
    updating: 'اپ ڈیٹ ہو رہا ہے...',
    yearsExperience: 'تجربے کے سال',
    bio: 'تعارف',
    bioPlaceholder: 'صارفین کو اپنے اور اپنے تجربے کے بارے میں بتائیں...',
    loadingError: 'پروفائل لوڈ کرنے میں ناکامی۔',
    actionFailed: 'دستیابی اپ ڈیٹ کرنے میں ناکامی۔',
    profileUpdatedToast: 'پروفائل اپ ڈیٹ ہو گیا!',
    updateError: 'پروفائل اپ ڈیٹ کرنے میں ناکامی۔',
    verified: 'تصدیق شدہ',
    unverified: 'تصدیق زیر التواء',
    viewMore: 'مزید دیکھیں',
    search: 'تلاش کریں',
    address: 'پتہ',
    description: 'تفصیل',
    title: 'عنوان',

    // My Bookings Dashboard
    viewOffers: 'آفرز دیکھیں',
    edit: 'ترمیم کریں',
    delete: 'حذف کریں',
    leaveReview: 'ریویو دیں',
    reviewSubmitted: 'ریویو جمع کر دیا گیا',
    workerOffers: 'ورکر کی آفرز',
    noOffersYet: 'ابھی تک کوئی آفر موصول نہیں ہوئی۔ براہ کرم ورکرز کے جواب کا انتظار کریں۔',
    acceptOffer: 'آفر قبول کریں',
    accepting: 'قبول ہو رہا ہے...',
    editJobPost: 'کام کی پوسٹ میں ترمیم کریں',
    jobTitle: 'کام کا عنوان',
    leaveAReview: 'ریویو دیں',
    rating: 'درجہ بندی',
    commentOptional: 'تبصرہ (اختیاری)',
    tellUsAboutExperience: 'ہمیں اپنے تجربے کے بارے میں بتائیں...',
    noBookingsYet: 'آپ نے ابھی تک کوئی بکنگ نہیں کی ہے۔',
    noFilteredBookings: 'کوئی {status} بکنگ نہیں ملی۔',
    offerAcceptedToast: 'آفر قبول کر لی گئی! ورکر کو مطلع کر دیا گیا ہے۔',
    jobDeletedToast: 'کام کی پوسٹ حذف کر دی گئی۔',
    jobUpdatedToast: 'کام کی پوسٹ کامیابی کے ساتھ اپ ڈیٹ ہو گئی!',
    reviewSubmittedToast: 'ریویو جمع ہو گیا! شکریہ۔',

    // Job Requests Dashboard (Worker)
    orCounterOffer: 'یا اپنی پیشکش دیں',
    yourPrice: 'آپ کی قیمت (روپے)',
    customPrice: 'اپنی قیمت',
    sendCustomOffer: 'اپنی آفر بھیجیں',
    sending: 'بھیجی جا رہی ہے...',
    yourBid: 'آپ کی بولی:',
    waitingForCustomer: 'گاہک کا انتظار ہے...',
    markCompleted: 'مکمل قرار دیں',
    completing: 'مکمل ہو رہا ہے...',
    rateCustomer: 'گاہک کی درجہ بندی کریں',
    ratedCustomer: 'گاہک کی درجہ بندی کر دی گئی',
    howWasExperienceWithCustomer: 'اس گاہک کے ساتھ آپ کا تجربہ کیسا رہا؟',
    noJobsFound: 'کوئی کام نہیں ملا',
    noPendingJobsDesc: 'اس وقت آپ کی سروس کی قسم کے لیے کوئی زیر التواء کام نہیں ہے۔',
    noOffersSentDesc: 'آپ نے ابھی تک کوئی آفر نہیں بھیجی ہے۔',
    noActiveJobsDesc: 'آپ کا کوئی فعال کام نہیں ہے۔',
    noCompletedJobsDesc: 'ابھی تک کوئی مکمل شدہ کام نہیں ہے۔',
    offerSentToast: 'آفر کامیابی کے ساتھ بھیج دی گئی!',
    jobAcceptedToast: 'کام قبول کر لیا گیا اور آپ کی فعال فہرست میں شامل کر دیا گیا!',
    jobCompletedToast: 'کام مکمل قرار دے دیا گیا!',
    customerReviewToast: 'گاہک کے لیے ریویو جمع کر دیا گیا!',

    // Book Service Page
    bookServiceSubtitle: 'تفصیلات پُر کریں اور ہم آپ کو ایک تصدیق شدہ پیشہ ور سے ملا دیں گے۔',
    jobTitlePlaceholder: 'مثال کے طور پر: ڈرائنگ روم کی لائٹ ٹھیک کرنی ہے',
    describeIssue: 'اپنے مسئلے کی وضاحت کریں',
    issuePlaceholder: 'مثال کے طور پر: میرے باورچی خانے کی لائٹ ٹمٹما رہی ہے...',
    serviceAddress: 'سروس کا پتہ',
    addressPlaceholder: 'پاکستان میں اپنا پتہ لکھیں...',
    jobPhotosOptional: 'کام کی تصاویر (اختیاری)',
    uploadPhoto: 'تصویر اپ لوڈ کریں',
    priceEstimateLabel: 'قیمت کا تخمینہ (روپے)',
    preferredDateTime: 'پسندیدہ تاریخ اور وقت',
    submitBooking: 'بکنگ جمع کروائیں',
    supportChat: 'سپورٹ چیٹ',
    onlineBotAgents: 'آن لائن | آٹو بوٹ اور ایجنٹس',
    howCanWeHelpYou: 'آج ہم آپ کی کیا مدد کر سکتے ہیں؟',
    typeYourMessage: 'اپنا پیغام لکھیں...',
    supportChats: 'سپورٹ چیٹس',
    searchUsers: 'صارفین تلاش کریں...',
    selectConversation: 'بات چیت شروع کرنے کے لیے ایک گفتگو منتخب کریں',
    respondToQueries: 'صارف کے سوالات کے جوابات دیں اور چیٹ کی تاریخ دیکھیں۔',
    typeAResponse: 'جواب لکھیں...',
    restartLiveServer: 'لائیو سرور دوبارہ شروع کریں',
    restartConfirm: 'کیا آپ واقعی تازہ ترین تبدیلیاں حاصل کرنا اور لائیو سرور کو دوبارہ شروع کرنا چاہتے ہیں؟',
    restarting: 'دوبارہ شروع ہو رہا ہے...',
    selectServiceType: 'براہ کرم سروس کی قسم منتخب کریں',
    bookingSubmittedToast: 'بکنگ جمع ہو گئی! ہم جلد ہی ایک ورکر مقرر کریں گے۔',
    suggestionsTitle: 'تجاویز (صرف پاکستان)',
    fileTooLarge: 'فائل بہت بڑی ہے۔ زیادہ سے زیادہ 5MB کی اجازت ہے۔',
    selectService: 'سروس منتخب کریں',
    editProfile: 'پروفائل میں ترمیم کریں',
    joined: 'شامل ہوئے',
    userReviews: 'صارفین کے ریویوز',
    noReviewsYet: 'ابھی تک کوئی ریویو موصول نہیں ہوا۔',
    untitledService: 'بغیر عنوان کے سروس',
    noCommentProvided: 'کوئی تبصرہ نہیں کیا گیا',
    recentJobs: 'حالیہ کام',
    noJobHistory: 'کام کی کوئی ہسٹری نہیں ہے۔',
    choosePhoto: 'تصویر منتخب کریں',
    profileUpdatedToast: 'پروفائل اپ ڈیٹ ہو گئی!',
    profileNotFound: 'پروفائل نہیں ملی۔',
    profilePicture: 'پروفائل تصویر',
    fileTypeLimit: 'PNG, JPG یا GIF، زیادہ سے زیادہ 5MB',

    // Home Page
    fastBooking: '60 سیکنڈ سے کم میں فاسٹ بکنگ',
    heroTitleMain: 'بھروسہ مند گھریلو',
    heroTitleSub: 'پیشہ ور افراد بک کریں',
    verifiedWorkersShort: 'تصدیق شدہ ورکرز',
    ratedReviewed: 'ریٹیڈ اور ریویوڈ',
    fastResponse: 'فوری رسپانس',
    howItWorks: 'یہ کیسے کام کرتا ہے',
    threeSteps: 'آپ کے مسئلے کو حل کرنے کے لیے 3 آسان اقدامات',
    whatCustomersSay: 'گاہک کیا کہتے ہیں',
    trustedHomeowners: 'ہزاروں گھر مالکان کا بھروسہ',
    readyToStart: 'شروع کرنے کے لیے تیار ہیں؟',
    ctaBannerDesc: 'ہزاروں خوش کن صارفین میں شامل ہوں۔ اپنی پہلی سروس 60 سیکنڈ سے کم میں بک کریں۔',
    pickAService: 'سروس کا انتخاب کریں',
    pickAServiceDesc: 'الیکٹریشن، پلمبر، اے سی ٹیکنیشن، یا بڑھئی میں سے انتخاب کریں۔',
    submitRequest: 'درخواست جمع کریں',
    submitRequestDesc: 'اپنے مسئلے کی وضاحت کریں اور سیکنڈوں میں اپنا پتہ شامل کریں۔',
    jobDone: 'کام مکمل',
    jobDoneDesc: 'ورکر آتا ہے، کام مکمل کرتا ہے، آپ انہیں ریٹ کرتے ہیں۔',
    happyCustomersLabel: 'خوش گاہک',
    jobsCompletedLabel: 'مکمل کام',
    avgRatingLabel: 'اوسط ریٹنگ',
    satisfactionRateLabel: 'اطمینان کی شرح',
    saraKhan: 'سارہ خان',
    homeowner: 'گھر کی مالک',
    saraTestimonial: 'سروس ناک کا الیکٹریشن 2 گھنٹے سے بھی کم وقت میں پہنچ گیا۔ انتہائی پیشہ ورانہ اور ہر چیز کو مکمل طور پر ٹھیک کر دیا!',
    aliHaider: 'علی حیدر',
    businessOwner: 'کاروبار کا مالک',
    aliTestimonial: 'ہمارے دفتر کے اے سی کی مرمت کے لیے سروس ناک کا استعمال کیا۔ تیز، سستا، اور ورکر تصدیق شدہ تھا۔ پرزور سفارش کرتا ہوں۔',
    asimIqbal: 'عاصم اقبال',
    apartmentTenant: 'اپارٹمنٹ کرایہ دار',
    asimTestimonial: 'رات 9 بجے سروس ناک سے پلمبر بک کیا اور صبح تک سب ٹھیک ہو گیا۔ ہمارے خاندان کے لیے حیرت انگیز رفتار اور معیار!',
    bilalSiddiqui: 'بلال صدیقی',
    interiorDesigner: 'انٹیریئر ڈیزائنر',
    bilalTestimonial: 'باورچی خانے کی الماریاں ٹھیک کرنے کے لیے سروس ناک سے بڑھئی ملا۔ غیر معمولی معیار اور بہت مناسب قیمت۔',
    maryamJaved: 'مریم جاوید',
    doctor: 'ڈاکٹر',
    maryamTestimonial: 'سروس ناک گھر کی کسی بھی مرمت کے لیے میری پہلی پسند ہے۔ ان کے ورکرز وقت کے پابند، ماہر اور بکنگ کا عمل بہت آسان ہے۔',
    zainabRaza: 'زینب رضا',
    teacher: 'استانی',
    zainabTestimonial: 'سروس ناک کے پلمبر سے انتہائی مطمئن ہوں۔ اس نے لیک کی جلد تشخیص کی اور بغیر کسی پریشانی کے اسے ٹھیک کر دیا۔',
    
    // Financials
    spendingTotal: 'کل خرچ',
    earningsTotal: 'کل آمدنی',
    urduNameLabel: 'اردو میں نام',

    // Privacy Policy
    privacyTitle: 'پرائیویسی پالیسی',
    lastUpdated: 'آخری بار اپ ڈیٹ کیا گیا: مئی 2026',
    infoCollect: '1. معلومات جو ہم جمع کرتے ہیں',
    infoCollectDesc: 'سروس ناک ایک محفوظ اور قابل اعتماد مارکیٹ پلیس فراہم کرنے کے لیے ذاتی معلومات جمع کرتا ہے۔ اس میں شامل ہے:',
    accountInfo: 'ذاتی تفصیلات: نام، ای میل، اور 11 ہندسوں کا تصدیق شدہ فون نمبر۔',
    bookingData: 'سروس ڈیٹا: کام کی تفصیل، پتے، اور مسئلے کی تصاویر۔',
    paymentData: 'شناختی دستاویزات: ورکرز کے لیے، ہم لازمی تصدیق کے لیے شناختی کارڈ (CNIC) کی تصاویر جمع کرتے ہیں۔ تصدیق اور پروفائل کی منظوری کے بعد آپ کے شناختی کارڈ کی تصویر مستقل طور پر حذف کر دی جاتی ہے — ہم آپ کا شناختی کارڈ محفوظ نہیں رکھتے۔',
    howWeUse: '2. ہم آپ کی معلومات کیسے استعمال کرتے ہیں',
    howWeUseDesc: 'آپ کی معلومات صرف صارفین اور سروس فراہم کرنے والوں کے درمیان رابطے کو آسان بنانے کے لیے استعمال ہوتی ہیں۔ ہم اسے استعمال کرتے ہیں:',
    connectCustomers: 'ورکرز کو اپنے علاقے میں کام کی درخواستیں دیکھنے کے قابل بنانا۔',
    sendNotifications: 'ایس ایم ایس یا پلیٹ فارم نوٹیفیکیشنز کے ذریعے ریئل ٹائم اپ ڈیٹس فراہم کرنا۔',
    customerSupport: 'صارفین کی حفاظت کو یقینی بنانے کے لیے پیشہ ور افراد کی شناخت کی تصدیق کرنا۔',
    platformAnalytics: 'تنازعات کو حل کرنا اور کسٹمر سپورٹ فراہم کرنا۔',
    dataSecurity: '3. ڈیٹا کی حفاظت اور شناختی کارڈ کا تحفظ',
    dataSecurityDesc: 'ہم شناختی ڈیٹا کو بہت سنجیدگی سے لیتے ہیں۔ شناختی کارڈ کی تصاویر صرف دستی تصدیق کے لیے استعمال ہوتی ہیں اور پروفائل کی منظوری کے بعد مستقل طور پر حذف کر دی جاتی ہیں۔ ہم آپ کا شناختی کارڈ محفوظ نہیں رکھتے۔',
    sharingThirdParties: '4. معلومات کا اشتراک',
    sharingThirdPartiesDesc: 'آپ کے رابطے کی معلومات (فون/پتہ) صرف اس وقت ورکر کے ساتھ شیئر کی جاتی ہیں جب آپ ان کی آفر قبول کر لیں۔ ہم آپ کا ڈیٹا کبھی بھی تھرڈ پارٹی مارکیٹنگ ایجنسیوں کو فروخت نہیں کرتے۔',
    yourRights: '5. آپ کے حقوق',
    yourRightsDesc: 'آپ کسی بھی وقت سپورٹ سے رابطہ کر کے اپنی پروفائل اپ ڈیٹ کر سکتے ہیں، ڈیٹا حذف کرنے کی درخواست کر سکتے ہیں، یا اپنی تصدیقی دستاویزات واپس لے سکتے ہیں، حالانکہ اس سے پلیٹ فارم تک آپ کی رسائی محدود ہو سکتی ہے۔',

    // Terms & Conditions
    termsTitle: 'شرائط و ضوابط',
    acceptanceTerms: '1. شرائط کی قبولیت',
    acceptanceTermsDesc: 'سروس ناک پر رجسٹر ہو کر، آپ ہمارے کمیونٹی معیارات اور سروس رولز کی تعمیل کرنے سے اتفاق کرتے ہیں۔ یہ پلیٹ فارم پاکستان میں مقامی گھریلو خدمات کے لیے ایک مارکیٹ پلیس ہے۔',
    userAccounts: '2. اکاؤنٹ کی ذمہ داری',
    userAccountsDesc: 'صارفین کو اصلی نام اور درست معلومات فراہم کرنی چاہئیں۔ ورکرز کو بولی لگانے سے پہلے لازمی شناختی کارڈ کی تصدیق مکمل کرنی ہوگی۔ پلیٹ فارم کا غلط استعمال یا جعلی پروفائلز کے نتیجے میں اکاؤنٹ کو مستقل طور پر بلاک کر دیا جائے گا۔',
    bookingPayments: '3. بولی اور قیمت کا تعین',
    bookingPaymentsDesc: 'ورکرز گاہک کی تفصیلات کی بنیاد پر "قیمت کی آفرز" فراہم کرتے ہیں۔ ایک بار آفر قبول ہو جانے کے بعد، یہ ایک رسمی معاہدہ تصور کیا جاتا ہے۔ گاہک کام مکمل ہونے پر پیشہ ور کو براہ راست ادائیگی کرنے کا ذمہ دار ہے۔',
    cancellationsTerms: '4. منسوخی',
    cancellationsTermsDesc: 'گاہکوں یا ورکرز کی جانب سے بار بار بکنگ منسوخ کرنے پر اکاؤنٹ پر پابندیاں لگ سکتی ہیں۔ ہم اپنے سروس پروفیشنلز کے وقت کی قدر کرتے ہیں۔',
    proVerification: '5. پیشہ ورانہ طرز عمل',
    proVerificationDesc: 'سروس ناک رابطے کے لیے ایک پلیٹ فارم ہے۔ اگرچہ ہم شناخت کی تصدیق کرتے ہیں، ہم ورکرز کو ملازمت پر نہیں رکھتے۔ آپ کے شناختی کارڈ کی تصویر تصدیق اور پروفائل کی منظوری کے بعد حذف کر دی جاتی ہے — ہم اسے مستقل طور پر محفوظ نہیں رکھتے۔ صارفین کو چاہیے کہ وہ عام احتیاط برتیں اور ادائیگی سے پہلے کام کی تصدیق کریں۔',
    liabilityLimitation: '6. ذمہ داری کی حد',
    liabilityLimitationDesc: 'سروس ناک ہماری خدمات کے استعمال یا پلیٹ فارم کے ذریعے حاصل کیے گئے آزاد ٹھیکیداروں کے اقدامات کے نتیجے میں ہونے والے کسی بھی بالواسطہ، اتفاقی، یا نتیجہ خیز نقصانات کا ذمہ دار نہیں ہوگا۔',
    voiceDescription: 'آواز کی تفصیل',
    speakIssue: 'بول کر بتائیں',
    stopRecording: 'ریکارڈنگ روکیں',
    recordingStarted: 'ریکارڈنگ شروع ہو گئی...',
    recordingStopped: 'ریکارڈنگ روک دی گئی۔',
    micError: 'مائیکروفون تک رسائی مسترد کر دی گئی۔',
    blockedAccountAlert: 'آپ کا اکاؤنٹ بلاک کر دیا گیا ہے، تفصیلات کے لیے سپورٹ سے رابطہ کریں۔',
    reportProfile: 'پروفائل کی رپورٹ کریں',
    reported: 'رپورٹ کر دیا گیا',
    confirmReport: 'کیا آپ واقعی اس پروفائل کی رپورٹ کرنا چاہتے ہیں؟ 3 رپورٹ ہونے پر یہ اکاؤنٹ خود بخود بلاک ہو جائے گا۔',
    verified: 'تصدیق شدہ',
    unverified: 'غیر تصدیق شدہ',
    identityVerification: 'شناختی تصدیق',
    verifyIdentityDesc: 'اپنے شناختی کارڈ کی واضح تصویر اپ لوڈ کر کے اپنی شناخت کی تصدیق کریں۔ اس سے کمیونٹی میں اعتماد بڑھتا ہے۔',
    uploadCNIC: 'شناختی کارڈ کی تصویر اپ لوڈ کریں',
    verificationPending: 'تصدیق زیر التوا ہے',
    verificationPendingDesc: 'آپ کے شناختی کارڈ کا ہماری ٹیم جائزہ لے رہی ہے۔ اس میں عام طور پر 24 گھنٹے لگتے ہیں۔',
    verificationRejected: 'تصدیق مسترد کر دی گئی',
    verificationRejectedReason: 'وجہ:',
    resubmitID: 'دوبارہ جمع کرائیں',
    submitForVerification: 'تصدیق کے لیے جمع کرائیں',
    verificationSuccess: 'تصدیق کے لیے درخواست جمع کر دی گئی ہے!',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');
  const [direction, setDirection] = useState(language === 'ur' ? 'rtl' : 'ltr');

  useEffect(() => {
    localStorage.setItem('language', language);
    const dir = language === 'ur' ? 'rtl' : 'ltr';
    setDirection(dir);
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    
    // Update fonts for Urdu
    if (language === 'ur') {
      document.body.style.fontFamily = "'Noto Nastaliq Urdu', serif, 'Inter', sans-serif";
    } else {
      document.body.style.fontFamily = "'Inter', system-ui, sans-serif";
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ur' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
